### ISSUE TITLE
ribor

### ISSUE THREAD

**Issue by mjgeng** [Bioconductor/Contributions#1200]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ribosomeprofiling/ribor

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor.  Please see the initial review below. 


**License/DESCRIPTION**

- [ ] R distributes with `GPL-3`. See https://www.r-project.org/Licenses/. I   think you therefore can remove the LICENSE file and change the Description to GPL-3.  This should remove the R Check NOTES too. 

- [ ] (optional) In the past we haven't found much benefit to using `LazyData: true` and in fact can periodically delay the installation of a package. 


**README**

- [ ] Please also include instructions for Bioconductor installation


**Build Report**

- [ ] Please fix the incomplete final lines

**inst/extdata and inst/scripts**

- [ ] Please include an `inst/scripts` directory with information on the source and how the files in `inst/extdata` were generated. This can be text, sudo code or straight code but information about the source of the data and some general idea of how the obejcts were created are required. 


**vignette**

- [ ] It seems like vignette and walkthrough contain the same information. Remove one (recommended deleting vignette.Rmd and walkthrough.Rmd seems more complete.).  We would also recommend having the vignette named something more intuitive and informative as generic names can result in conflicts with other packages.  Having a vignette the same name as the package as can be very intuitive for a user so they can just go:

```
vignette("ribor")
```

**vignette.Rmd** (although recommend removing completely since it is duplicated in the other vignette)

- [ ] Please give your vignette a meaningful name. Calling a package vignette can cause naming conflicts. 

- [ ] Type line 62 "quick look at the contentsd of the" 

- [ ] Can you normalize without plotting? 



**walkthrough.Rmd**

- [ ] Include Bioconductor installation instructions




**R code / man files**

**ribor.R**
- [ ] I recommend pointing the users to your vignette or main functions in your package documentation


**General**

- [ ] For data that takes or can take the form of feature/sample (count data, etc) ideally we would like to see SummarizedExperiments over matricies/data.frames. Not sure how well this would play with your data class structures and the hdf5 backend.    Can you briefly explain why no existing Bioconductor class structure was sufficient to use or to extend for your data?  We really try to encourage interoperability. 

- [ ] Since this has the potential to be a newly recommended way of importing a different file type I am asking @hpages and @mtmorgan to quickly glance and provide any comments if they wish. 


Thank you for your submission.  Please see above comments.  We look forward to working with you on getting your package accepted into Bioconductor.  Please also remember to set up your [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) so that version bumps will trigger new builds of the package.  

Cheers, 
Lori

**Comment by mjgeng** [comment]
Thank you for the response and suggestions!

The vignettes have been edited since the time of submission, and I will have to look into the SummarizedExperiments class and get back to you on its implementation. The rest of the notes will be addressed and fixed.

As a note, we will likely not be able to work on this until the beginning of September, so it may be some time before I submit the updated package. 

Until then, if there is any other feedback, we will be happy to address and incorporate it.

**Comment by mjgeng** [comment]
Hi. Most of the changes with respect to the vignettes, license, and package statement have been addressed. Once the inst/script directory is added, we will push the build.

However, we are not sure about implementing SummarizedExperiment in ribor after reading its documentation. For example, the outputs of many of our data reading functions vary based on the parameters, and often times data is summed across transcripts, eliminating information at the transcript-specific level. Additionally, we currently present options to return the data as tidy for any downstream filtering and plotting. From our understanding, SummarizedExperiment does not appear to be as useful for these cases.

For our use cases so far, we have been pretty content with the data.table objects, and it has served our purposes as an efficient and consistent output across any combination of parameters.

**Comment by lshep** [comment]
Just checking back in -  If you have the other updates ready please don't forget to do a version bump and push changes to kick off a new build.  If summarizedExperiment isn't appropriate don't worry about that update.

**Comment by hpages** [comment]
Hi,

I took a quick look at this submission and found the following problems.

### data.table objects

Internal use of the data.table package in your package might be ok but we discourage exposing data.table objects to the end user. That's because these objects use a reference semantic which is non-standard in R and they also require a special syntax. So unless you have a very good reason to return data.table objects to the end user, we strongly recommend that you use ordinary data frames or DataFrame objects. This will make your package fit more nicely in the Bioconductor ecosystem.
Now, after taking a closer look at where and how you use data.table objects, I'm not convinced that their use is justified.

#### Let's start with `get_coverage()`

This function returns the coverage data in a data.table object. However, I will argue that this data is conceptually a matrix, not a data.frame. That's because the data is homogeneous i.e. all the values have the same nature (they are coverage counts). Note that by returning the data in a matrix instead of a data.table object, you reduce its memory footprint _a lot_:
```
library(ribor)
path <- system.file("extdata", "HEK293_ingolia.ribo", package="ribor")
ribo <- create_ribo(path)

cvg <- get_coverage(ribo, get_reference_names(ribo)[[4]])
class(cvg)
# [1] "data.table" "data.frame"
object.size(cvg)
# 491104 bytes

## Store the coverage data in a matrix:
cvg2 <- as.matrix(cvg[ , -1])
rownames(cvg2) <- cvg[[1]]
object.size(cvg2)
# 184304 bytes
```
Also now you're using a data structure that is conceptually appropriate. Last but not least, your users can immediately use things like `rowSums()` on it, or any other row/col summarization method provided by the matrixStats package.

#### Now let's look at `get_rnaseq()`

If you return a DataFrame object (defined in the S4Vectors package) instead of a data.table, and use factor-Rle objects instead of plain character vectors for some of your columns, you will achieve a more compact representation:
```
rnaseq <- get_rnaseq(ribo)
class(rnaseq)
# [1] "data.table" "data.frame"
object.size(rnaseq)
# 9836528 bytes

## Store the RNA-seq data in a DataFrame instead:
library(S4Vectors)
rnaseq2 <- DataFrame(experiment=Rle(factor(rnaseq$experiment)),
                     transcript=factor(rnaseq$transcript),
                     region=Rle(factor(rnaseq$region)),
                     count=as.integer(rnaseq$count))
object.size(rnaseq2)
# 5241904 bytes
```
Memory footprint is reduced by almost half. And the bigger the data, the more reduction you'll get.

So overall there doesn't seem to be any benefit in using the data.table package.

### Open connection stored inside ribo objects

There are several problems with storing the open connection (H5IdComponent) to the HDF5 file in your objects. First the connection should be open in read-only mode (my understanding is that operations on ribo objects should never try to alter the `.ribo` file). Another problem is that right now the connection never gets closed, even after a ribo object gets removed from the session and garbage-collected. To avoid this, the usual recommendation is to register a finalizer function somewhere in the object (with `reg.finalizer()`) that will close the connection when the object gets garbage collected. But even these fixes won't address a fundamental issue that these connections will break in the context of parallel processing. An easy way to avoid all these problems is to store the **path** to the file instead of an open connection to it. Note that the path stored in the object should be **absolute** otherwise the object will break when the user changes the working directory (e.g. with `setwd()`). You can turn a user-supplied path into an absolute path with `tools::file_path_as_absolute()`.

### Other minor issues

- The Bioconductor convention is to use class names that start with a capital letter e.g. `Ribo` instead of `ribo`. Also the constructor function (`create_ribo()`) should normally be named like the class itself i.e. `Ribo()`.
 
- Not sure what's the point of storing the experiment names in the `experiments` slot of the object if `get_experiments()` ignores this slot and retrieves the names from the file each time it's called.

H.

**Comment by lshep** [comment]
I just wanted to check in on how the updates that myself and Herve suggested were going?

**Comment by mjgeng** [comment]
Hi. Yes! I am making the updates right now. The @handle slot is no longer an H5IdComponent, and we will be accessing the file with the absolute path as suggested. We are making the switch to DataFrames  and plan on changing the coverage return to a matrix.  Sorry for the delay.

**Comment by lshep** [comment]
Could we have another status update since its been another month?  If you need more time to work on the package we can temporarily close the issue and reopen it when you are ready to push changes.

**Comment by mjgeng** [comment]
Hello. We will be pushing our new changes to the repository shortly. We replaced the handle field in the ribo object with an path field that stores the absolute file path. We also used run length encoding and factors in our new DataFrame return format.

**Comment by lshep** [comment]
Thank you for the update.  when you are ready to push changes ping us here and we will reopen the issue and resume the review process.  cheers

**Comment by mjgeng** [comment]
Hello. We updated the repository last Friday, but the webhook failed since the issue was closed. As soon as it's open, I will resend the request. Have a good Thanksgiving!

**Comment by lshep** [comment]
Please try now and let me know if you have any other issue triggering

**Comment by mjgeng** [comment]
The error is encountered during the building of the vignettes. I can build locally with the same version without this issue, and I cannot currently reproduce the error. Does this have to do with some missing dependencies with R 4.0?

**Comment by lshep** [comment]
I can reproduce this error locally.  Please make sure you are using R-devel  (R 4.0)  and have the latest version of all Bioconductor packages by running `BiocManager::install(version = "devel")` and updating your package versions.

**Comment by mjgeng** [comment]
Hello.

The package now builds on two systems. However, on the Linux build, we get this dependency problem, and if you have any insight on what we can do to resolve this, please let us know. I imagine it's that 'tidyr' is just not available for Linux on the developer branch yet since the other systems built.

```
ERROR: dependency tidyr is not available for package ribor
* removing /tmp/Rtmp7ddDe8/Rinst469b3115c124/ribor
```
Additionally, we did not update the version dependency to 4.0.0 in DESCRIPTION just yet since we have some users who are not on the R-devel branch. 

> Thank you for your submission to Bioconductor. Please see the initial review below.
> 
> **License/DESCRIPTION**
> 
> * [ ]  R distributes with `GPL-3`. See https://www.r-project.org/Licenses/. I   think you therefore can remove the LICENSE file and change the Description to GPL-3.  This should remove the R Check NOTES too.

Fixed. 

> * [ ]  (optional) In the past we haven't found much benefit to using `LazyData: true` and in fact can periodically delay the installation of a package.
> 

We changed the LazyData to false.

> **README**
> 
> * [ ]  Please also include instructions for Bioconductor installation
> 

Our related paper is currently in review, and we want to avoid any incompatibilities with downloading the package since RiboR is still in review for Bioconductor. We will add this shortly.

> **Build Report**
> 
> * [ ]  Please fix the incomplete final lines
> 
> **inst/extdata and inst/scripts**
> 
> * [ ]  Please include an `inst/scripts` directory with information on the source and how the files in `inst/extdata` were generated. This can be text, sudo code or straight code but information about the source of the data and some general idea of how the obejcts were created are required.
> 
> **vignette**
> 
> * [ ]  It seems like vignette and walkthrough contain the same information. Remove one (recommended deleting vignette.Rmd and walkthrough.Rmd seems more complete.).  We would also recommend having the vignette named something more intuitive and informative as generic names can result in conflicts with other packages.  Having a vignette the same name as the package as can be very intuitive for a user so they can just go:

We now only have a single ribor.Rmd file.

> 
> ```
> vignette("ribor")
> ```
> 
> **vignette.Rmd** (although recommend removing completely since it is duplicated in the other vignette)
> 
> * [ ]  Please give your vignette a meaningful name. Calling a package vignette can cause naming conflicts.
> * [ ]  Type line 62 "quick look at the contentsd of the"

We made pretty significant modifications to the vignette, and there is only one vignette named ribor.Rmd. 

> * [ ]  Can you normalize without plotting?

Yes. We have included the 'normalize' parameter in the reading functions.

> 
> **walkthrough.Rmd**
> 
> * [ ]  Include Bioconductor installation instructions

We went ahead and added this in the vignette, and we will modify the readme soon.

> **R code / man files**
> 
> **ribor.R**
> 
> * [ ]  I recommend pointing the users to your vignette or main functions in your package documentation

Yes, now typing ?ribor will have some helpful information.

> **General**
> 
> * [ ]  For data that takes or can take the form of feature/sample (count data, etc) ideally we would like to see SummarizedExperiments over matricies/data.frames. Not sure how well this would play with your data class structures and the hdf5 backend.    Can you briefly explain why no existing Bioconductor class structure was sufficient to use or to extend for your data?  We really try to encourage interoperability.

This will be addressed below.

> * [ ]  Since this has the potential to be a newly recommended way of importing a different file type I am asking @hpages and @mtmorgan to quickly glance and provide any comments if they wish.
> 

> ### data.table objects
> Internal use of the data.table package in your package might be ok but we discourage exposing data.table objects to the end user. That's because these objects use a reference semantic which is non-standard in R and they also require a special syntax. So unless you have a very good reason to return data.table objects to the end user, we strongly recommend that you use ordinary data frames or DataFrame objects. This will make your package fit more nicely in the Bioconductor ecosystem.
> Now, after taking a closer look at where and how you use data.table objects, I'm not convinced that their use is justified.
> 

We have now fully switched to DataFrame/DFrame with all of the returned data frames. We apply Rle and factor to the redundant columns (experiment, transcript, region, read length).

> #### Let's start with `get_coverage()`
> This function returns the coverage data in a data.table object. However, I will argue that this data is conceptually a matrix, not a data.frame. That's because the data is homogeneous i.e. all the values have the same nature (they are coverage counts). Note that by returning the data in a matrix instead of a data.table object, you reduce its memory footprint _a lot_:
> 
> ```
> library(ribor)
> path <- system.file("extdata", "HEK293_ingolia.ribo", package="ribor")
> ribo <- create_ribo(path)
> 
> cvg <- get_coverage(ribo, get_reference_names(ribo)[[4]])
> class(cvg)
> # [1] "data.table" "data.frame"
> object.size(cvg)
> # 491104 bytes
> 
> ## Store the coverage data in a matrix:
> cvg2 <- as.matrix(cvg[ , -1])
> rownames(cvg2) <- cvg[[1]]
> object.size(cvg2)
> # 184304 bytes
> ```
> 
> Also now you're using a data structure that is conceptually appropriate. Last but not least, your users can immediately use things like `rowSums()` on it, or any other row/col summarization method provided by the matrixStats package.
> 

We provide the option of storing the coverage information in a tidy format alongside preserving individual read lengths, so we decided to keep the DataFrame structure as the return value.

> #### Now let's look at `get_rnaseq()`
> If you return a DataFrame object (defined in the S4Vectors package) instead of a data.table, and use factor-Rle objects instead of plain character vectors for some of your columns, you will achieve a more compact representation:
> 
> ```
> rnaseq <- get_rnaseq(ribo)
> class(rnaseq)
> # [1] "data.table" "data.frame"
> object.size(rnaseq)
> # 9836528 bytes
> 
> ## Store the RNA-seq data in a DataFrame instead:
> library(S4Vectors)
> rnaseq2 <- DataFrame(experiment=Rle(factor(rnaseq$experiment)),
>                      transcript=factor(rnaseq$transcript),
>                      region=Rle(factor(rnaseq$region)),
>                      count=as.integer(rnaseq$count))
> object.size(rnaseq2)
> # 5241904 bytes
> ```
> 
> Memory footprint is reduced by almost half. And the bigger the data, the more reduction you'll get.
> 
> So overall there doesn't seem to be any benefit in using the data.table package.

We adjusted all of the reading functions (get_rnaseq, get_metagene, get_length_distribution, get_coverage, get_region_counts) to return DataFrames and applied the Rle and factor functions to optimize the memory footprint.

> ### Open connection stored inside ribo objects
> There are several problems with storing the open connection (H5IdComponent) to the HDF5 file in your objects. First the connection should be open in read-only mode (my understanding is that operations on ribo objects should never try to alter the `.ribo` file). Another problem is that right now the connection never gets closed, even after a ribo object gets removed from the session and garbage-collected. To avoid this, the usual recommendation is to register a finalizer function somewhere in the object (with `reg.finalizer()`) that will close the connection when the object gets garbage collected. But even these fixes won't address the fundamental issue that these connections will break in the context of parallel processing. An easy way to avoid all these problems is to store the **path** to the file instead of an open connection to it. Note that the path stored in the object should be **absolute** otherwise the object will break when the user changes the working directory (e.g. with `setwd()`). You can turn a user-supplied path into an absolute path with `tools::file_path_as_absolute()`.
>

We now replaced the 'handle' attribute of the ribo file with a 'path' attribute, using file_path_as_absolute(). All uses of the rhdf5 functions now provide the stored absolute path instead of a file handle.

> ### Other minor issues
> * The Bioconductor convention is to use class names that start with a capital letter e.g. `Ribo` instead of `ribo`. Also the constructor function (`create_ribo()`) should normally be named like the class itself i.e. `Ribo()`.

For now, we have kept the create_ribo() as the constructor.

> * Not sure what's the point of storing the experiment names in the `experiments` slot of the object if `get_experiments()` ignores this slot and retrieves the names from the file each time it's called.
> 

This was just a safe guard. We store the experiments locally for the user to simply reference, and it is safer for us to just read from the .ribo file every time to ensure that any unintended user modifications to the ribo object do not show up in the reading functions.

**Comment by lshep** [comment]
Could you do a version bump as the tag indicates?  It seems you may have pushed more changes that aren't currently reflected?

**Comment by mjgeng** [comment]
Hello,

Pardon me for not doing so sooner. I had to remove the .Rproj folder to get rid of the error. The only warning now is the R version dependency, which I would like to keep at 3.6.0 because a number of the people using the package are not on the devel version quite yet. The rest of the responses are above.

Best,
Michael

**Comment by hpages** [comment]
Hi @mjgeng,

Thanks for the changes. It's great that you were able to no longer use data.table objects.

A few more comments: 

> We provide the option of storing the coverage information in a tidy format alongside the option of preserving individual read lengths, so we decided to keep the DataFrame structure as the return value.

Using a DataFrame makes indeed plenty of sense for the tidy format. However, it still doesn't make sense to use a data-frame-like object to represent the matrix of counts (for the reason I explained earlier).

Also the `Value` section in `?get_coverage` needs to explain how the data is organized in the returned object. It's not enough to say "A data table containing the coverage data", especially since the format of the returned object is drastically different depending on whether the user sets `tidy` to `TRUE` or not. BTW it's no longer the case that the returned object is a _data table_ (and you need to correct a few other places in your documentation where you still say "data table").

> We store the experiments locally for the user to simply reference.

But you are not providing any accessor for this slot and since users are not supposed to use direct slot access (e.g. to do things like `ribo@experiments`) then the slot is useless. Remember that you need to provide a set of accessors if you want to allow your users to access parts of your objects (you don't have to provide accessors for everything in the object, only for the components that you actually want to expose to the user). 

A couple of other things:

- Please rename the `ribo` class `Ribo` (as I said, the Bioconductor convention is to use class names that start with a capital letter).

- You use direct slot access in various places in your code e.g. `DF@metadata[[1]] <- ...` (in helper_functions.R) or `info <- x@metadata[[1]]` (in metagene_functions.R). This is **strongly** discouraged. Please **always** use accessor functions to access components of an object that is implemented in an other package.

- The standard way to check that an object belongs to (or derives from) a given class is with `is(ribo, "ribo")`. There is no need for you to provide an `is.ribo` function for that, especially since the semantic of your function differs from `is(ribo, "ribo")`:
    ```
    setClass("ribo_extension", contains="ribo")
    riboext <- as(ribo, "ribo_extension")
    is(riboext, "ribo")
    # [1] TRUE
    is.ribo(riboext)
    # [1] FALSE
    ```

- A note about _object validity_: the man page for `is.ribo` says:
    ```
    The function ‘is.ribo’ checks whether or not a given ribo object is valid.
    ```
    Please note that the notion of _object validity_ is precisely and formally defined in the S4 class system. The important bit is that it's not enough for an object to belong to a class to be a valid instance of the class. All what your `is.ribo` function does is indicate whether an object _is_ a ribo object or not, but it does not say whether the object is _valid_ or not.

    For example, if the user had managed to modify the content of the `experiments` slot of a ribo object, then the object should be considered invalid. The standard way to check that an object is valid is by calling `validObject()` on it. However this only works properly if a _validity method_ was implemented for the object. Supposing that you decided to implement a validity method for ribo objects, and that you decided to keep the `experiments` slot, then the method could check that the content of the slot matches what's in the HDF5 file. Then calling `validObject()` on a ribo object where the `experiments` slot has been altered would return an error describing the problem.

    Implementing validity methods is a powerful and effective way to improve software robustness, reliability, and maintainability. This is why author/maintainers of a complex class are encouraged to implement a validity method for their objects.

Cheers,
H.

**Comment by mjgeng** [comment]
> Using a DataFrame makes indeed plenty of sense for the tidy format. However, it still doesn't make sense to use a data-frame-like object to represent the matrix of counts (for the reason I explained earlier).

Currently, get_coverage does not return a matrix of counts if tidy = FALSE. We provide the user the option of retrieving the counts at each individual read length and for individual experiment. I think it becomes difficult to annotate this in an intuitive manner, and I would prefer having a data frame as a consistent return value for the function. If you have any suggestions for this, please let me know.

> Also the `Value` section in `?get_coverage` needs to explain how the data is organized in the returned object. It's not enough to say "A data table containing the coverage data", especially since the format of the returned object is drastically different depending on whether the user sets `tidy` to `TRUE` or not. BTW it's no longer the case that the returned object is a _data table_ (and you need to correct a few other places in your documentation where you still say "data table").
> 

This has been corrected. No man pages should say data table.


> But you are not providing any accessor for this slot and since users are not supposed to use direct slot access (e.g. to do things like `ribo@experiments`) then the slot is useless. Remember that you need to provide a set of accessors if you want to allow your users to access parts of your objects (you don't have to provide accessors for everything in the object, only for the components that you actually want to expose to the user).

We have added accessors for all of the slots. One remaining thing is the warning message . I was searching to find a way to nest all of the accessor methods in the newly named `Ribo` constructor function man page, but I am still confused on how to properly do this . For now, I put all of them together in accessors.Rd. If you have any insight into documenting this in a more organized manner, please let me know. 

> A couple of other things:
> 
> * Please rename the `ribo` class `Ribo` (as I said, the Bioconductor convention is to use class names that start with a capital letter).

`ribo` has been renamed to `Ribo`.

> * You use direct slot access in various places in your code e.g. `DF@metadata[[1]] <- ...` (in helper_functions.R) or `info <- x@metadata[[1]]` (in metagene_functions.R). This is **strongly** discouraged. Please **always** use accessor functions to access components of an object that is implemented in an other package.

We now use the metadata accessor and mutator of the DataFrame class.

> * The standard way to check that an object belongs to (or derives from) a given class is with `is(ribo, "ribo")`. There is no need for you to provide an `is.ribo` function for that, especially since the semantic of your function differs from `is(ribo, "ribo")`:
>   ```
>   setClass("ribo_extension", contains="ribo")
>   riboext <- as(ribo, "ribo_extension")
>   is(riboext, "ribo")
>   # [1] TRUE
>   is.ribo(riboext)
>   # [1] FALSE
>   ```
> * A note about _object validity_: the man page for `is.ribo` says:
>   ```
>   The function ‘is.ribo’ checks whether or not a given ribo object is valid.
>   ```

Thank you for this. We removed the is.ribo function. Instead, we simply call validObject() or use is(object, "Ribo"). 
>   
>   Please note that the notion of _object validity_ is precisely and formally defined in the S4 class system. The important bit is that it's not enough for an object to belong to a class to be a valid instance of the class. All what your `is.ribo` function does is indicate whether an object _is_ a ribo object or not, but it does not say whether the object is _valid_ or not.
>   For example, if the user had managed to modify the content of the `experiments` slot of a ribo object, then the object should be considered invalid. The standard way to check that an object is valid is by calling `validObject()` on it. However this only works properly if a _validity method_ was implemented for the object. Supposing that you decided to implement a validity method for ribo objects, and that you decided to keep the `experiments` slot, then the method could check that the content of the slot matches what's in the HDF5 file. Then calling `validObject()` on a ribo object where the `experiments` slot has been altered would return an error describing the problem.
>   Implementing validity methods is a powerful and effective way to improve software robustness, reliability, and maintainability. This is why author/maintainers of a complex class are encouraged to implement a validity method for their objects.

Again, thank you for the input. We updated the validity method to check the slot values against the .ribo file.

> Cheers,
> H.

**Comment by hpages** [comment]
Thanks for all these changes.

See the man page for Factor (`?Factor`) in the S4Vectors package for an example of how to document an S4 class and its accessors.

You say that you want `get_coverage()` to return a DataFrame (by default, i.e. when `compact=TRUE`) because you want to be able to annotate it but OTOH the man page of the function doesn't say anything about the returned object being annotated.

So again, the `Value` section in `?get_coverage` needs to provide a lot more details. In particular it should explain how the data is organized in the returned object (e.g. what are the rows and columns for the different combinations of the `length` and `tidy` arguments), and, if the object is annotated, how these annotations can be accessed and what they are. Your users shouldn't need to make any guess about what they get. 

2 more things:

- The name of the `length` argument is counter-intuitive: if I set the argument to FALSE then `get_coverage()` adds a `length` column to the returned object but if I set it to TRUE then it does NOT. Please use a more intuitive name for this argument e.g. `sum.across.lengths` or `aggregate.by.length`. Yes it's a little bit longer but the extra clarity is worth it.

- Only use an Rle when you expect that their use will be beneficial. In the case of the `length` column (returned by `get_coverage()` when `length=FALSE`), there is no benefit in using an Rle, all the contrary.

Thanks for all your work on the package so far.

H.

**Comment by lshep** [comment]
@mjgeng   Any progress on the above changes suggested by @hpages ?

**Comment by mjgeng** [comment]
Pardon me for the delayed response. The changes will be out by the end of week. If there are any other suggestions aside from the ones above, please let me know. 

Best,
Michael

**Comment by mjgeng** [comment]
> Thanks for all these changes.
> 
> See the man page for Factor (`?Factor`) in the S4Vectors package for an example of how to document an S4 class and its accessors.

We tried to emulate it to the best of our abilities using roxygen2.

> You say that you want `get_coverage()` to return a DataFrame (by default, i.e. when `compact=TRUE`) because you want to be able to annotate it but OTOH the man page of the function doesn't say anything about the returned object being annotated.
> 
> So again, the `Value` section in `?get_coverage` needs to provide a lot more details. In particular it should explain how the data is organized in the returned object (e.g. what are the rows and columns for the different combinations of the `length` and `tidy` arguments), and, if the object is annotated, how these annotations can be accessed and what they are. Your users shouldn't need to make any guess about what they get.

We added more extensive documentation on the return values for get_coverage, get_region_counts, and get_metagene. Please let me know if this is sufficient. Additionally, we spent a lot of time on the vignette and hope that it helps to clear any confusion for any users. 

> 2 more things:
> 
> * The name of the `length` argument is counter-intuitive: if I set the argument to FALSE then `get_coverage()` adds a `length` column to the returned object but if I set it to TRUE then it does NOT. Please use a more intuitive name for this argument e.g. `sum.across.lengths` or `aggregate.by.length`. Yes it's a little bit longer but the extra clarity is worth it.

Thank you for bringing this up. As it stands, we have not changed these parameters, but hope to introduce it. The paper associated with this package has been out for a few months now, and because transcript and length are important parameters, we want to be wary of this much change in breaking the compatibility of any scripts using this package. We will likely change the parameter name or otherwise add clarity. We hope that the documentation and vignettes are clear enough to acquaint the user with these packages in the time being.

> * Only use an Rle when you expect that their use will be beneficial. In the case of the `length` column (returned by `get_coverage()` when `length=FALSE`), there is no benefit in using an Rle, all the contrary.

Thank you for this. Rle is no longer being used on the length column in the return values of any of our functions.

> Thanks for all your work on the package so far.
> 
> H.

**Comment by hpages** [comment]
These changes look good. Please fix the remaining warnings. Not sure why you're not citing the associated paper in the vignette and/or in the package man page (`ribor.Rd`).

**Comment by mjgeng** [comment]
The last remaining warning is in reference to the R version being 3.6.0 and later instead of 4.0.0 and later. Does this have to be changed if the package supports 3.6.0 onwards?

**Comment by hpages** [comment]
That warning can be ignored. Package accepted. Thanks for your contribution!

H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mjgeng.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ribor")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ribor

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
