### ISSUE TITLE
SingleCellSignalR

### ISSUE THREAD

**Issue by SCA-IRCM** [Bioconductor/Contributions#1332]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SCA-IRCM/SingleCellSignalR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
robust and interoperable code implies reuse of standard data representations, in particular the SingleCellExperiment class / package. Please update your code to use this.

**Comment by hpages** [comment]
Hi @SCA-IRCM ,

The naming style of your functions is inconsistent:
```
> ls('package:SingleCellSignalR')
 [1] "cell_classifier"      "cell_signaling"       "cluster_analysis"    
 [4] "clustering"           "data_prepare"         "example_dataset"     
 [7] "expression.plot"      "expression.plot.2"    "inter_network"       
[10] "intra_network"        "LRdb"                 "markers"             
[13] "markers.default"      "mm2Hs"                "mv_interactions"     
[16] "PwC_ReactomeKEGG"     "score"                "simplifyInteractions"
[19] "visualize"           
```
Please choose a style and stick to it.

Don't use a generic name like `visualize` for a very specialized plotting function.

Your `score` function will conflict with the `score` generic function defined in the BiocGenerics package. (Bioconductor is an ecosystem and you want to make sure that your package fits nicely in it by cohabiting peacefully with the other packages in the ecosystem.)

Plotting function `expression.plot.2` doesn't plot anything.

Thanks!

**Comment by hpages** [comment]
Hello?

**Comment by SCA-IRCM** [comment]
Hello?

**Comment by SCA-IRCM** [comment]
Yes what can I do for you?

**Comment by hpages** [comment]
Good to hear your voice ;-)

So is the package ready for review?

**Comment by SCA-IRCM** [comment]
Hi,
I thought it was already under review. Following the indications from the message you sent on january 9th:
1. I changed the names of the functions so their style is consistent. 
2. I changed the `visualize()` function into `visualize_interaction()`
3. I changed the `score()` function into `LRscore()`
4. The example in the (now called) `expression_plot_2()` function plots something.

Is there anything else I need to do?
Otherwise I think it is ready for review :).

**Comment by hpages** [comment]
My message from January 9th were just some quick preliminary remarks. I'll take a closer look at the package in the next few days. Thanks!

**Comment by hpages** [comment]
Please address the following issues:

1. The _Contents_ section at the beginning of the vignette is out-of-sync with the real content. For example the name of section "Details of each function" in _Contents_ is different from its real name. Also its nesting level in _Contents_ is different from its real nesting level (it's listed as a subsection in _Contents_ but is a top-level section in the document). Finally sections are numbered in _Contents_ but not in the body of the vignette.
    Please use a standard mechanism to automatically generate the _Contents_ section from the real content. The main reason this kind of mechanism exists is to avoid the out-of-sync problem (and also to save you some work).

2. Half of the vignette is a copy/paste of the man pages of the functions defined in the package. Two problems with this: (1) this has no place in the vignette, (2) this kind of copy/paste is guaranteed to lead to an out-of-sync problem, again (but more serious in this case than with your _Contents_ section).
    Note that all the man pages will be **automatically** compiled in a PDF document called "Reference Manual" that we make available on the package landing page. See for example: https://bioconductor.org/packages/SummarizedExperiment They do this on CRAN too! Unlike a document obtained by copy/past'ing, the Reference Manual is guaranteed to stay in sync with the real man pages.

3. Please provide a **running** example for `data_prepare()`. FWIW you're misusing `\donttest` here i.e. code inside `\donttest` must be valid. See "[2.1.1 Documenting functions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Documenting-functions)" in the Writing R Extensions manual. Note that I'm NOT suggesting that you keep `\donttest`. What I'm asking is that you provide a running example that is NOT inside a `\donttest` or `\dontrun` so `R CMD check` and `example(data_prepare)` will **both** run it. 

Thanks!

**Comment by SCA-IRCM** [comment]
Hello,
Thank's for your review, I'll correct everything today. I just have a question/remark for the point 2. It is not just a copy/paste of the man pages of the function. Much more details are provided in the section called **Details**, do I copy/paste this information into the @return section of every function so that will appear in the Reference Manual?
I would really appreciate a quick answer so I can finish this as soon as possible.
Thank you in advance.

**Comment by SCA-IRCM** [comment]
Hi,
I fixed the three points you raised.
For the point 2. I finally added a @details sections in the functions descriptions, I think/hope it will be OK :).
I wait for your confirmation.
Yours,

SCA

**Comment by hpages** [comment]
The man page of a function is where you put everything you want to say about it. It doesn't really make sense to have 2 versions of a man page: a short/incomplete one accessible via `?cell_classifier` and an extended/complete one in the vignette. The user really expects to see all the information in the standard place, which is the real man page (i.e. the page accessible via `?cell_classifier`). So yes please merge whatever you have in the vignette into the real man pages and remove the "extended man pages" from the vignette. This duplication is not needed and is almost certain to cause problems in the long run.

More generally speaking, you should apply the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), which is an important aspect of good software engineering. It also applies to the documentation of the software.

Thanks!

**Comment by SCA-IRCM** [comment]
Yes of course, I understand what you mean. I proceeded to the consequent changes and the package is ready to review.
Thank you!

**Comment by hpages** [comment]
Hi,

The example in the man page for `data_prepare()` is still not doing anything:
```
> data = data_prepare(file = "~/scRNAseq_dataset.txt",write = FALSE)
~/scRNAseq_dataset.txt doesn't exist.
```
By "a running example for `data_prepare()`" I meant an example that actually shows the function **in action**. It is not useful and it is counter-productive that you've modified the function so that it no longer fails when supplied invalid arguments, just so that you can remove the `\donttest` or `\dontrun` from around the call.

Also please always use `<-` for assignments instead of `=`.

Thanks,
H.

**Comment by SCA-IRCM** [comment]
Hi, 
I've made the changes you ask. The package is ready for review.
Thanks

**Comment by hpages** [comment]
Hi,

> I've made the changes you ask.

Sorry but I don't see that:
```
> data <- data_prepare(file="./inst/scRNAseq_dataset.txt")
./inst/scRNAseq_dataset.txt doesn't exist.
```
I hope you realize that trying to access the file via "./scRNAseq_dataset.txt" or "./inst/scRNAseq_dataset.txt" is obviously a bad idea. The right thing to use here is `system.file` (see `?system.file`). This is basic knowledge.

Also all your functions are currently handling invalid input by printing a message (with `cat()`) and returning normally instead of using `stop()`. As I mentioned earlier, this is not useful and is in fact counter-productive. What they need to do instead is raise an error, a _real_ one, with `stop()`. This is very basic stuff in software design. Please revisit all your functions and make sure they handle errors properly.

Thanks,
H.

**Comment by SCA-IRCM** [comment]
Hi,
I think I have made the changes you asked for. If there is something more to do I'll be happy to do it :).
Thanks

SCA

**Comment by hpages** [comment]
Thanks for making these changes. Package is good to go know.

Cheers,
H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/SCA-IRCM.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SingleCellSignalR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SingleCellSignalR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
