### ISSUE TITLE
cmapR submission

### ISSUE THREAD

**Issue by tnat1031** [Bioconductor/Contributions#1335]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cmap/cmapR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
I haven't looked closely at the package but it seems like the basic data structure (matrix of values + row / column annotations) should contain SummarizedExperiment or perhaps use HDF5Array as the assay data of SummarizedExperiment. Also the DESCRIPTION:Description field (and title?) should be written so that someone who doesn't know what 'cmap' is can find out!

**Comment by tnat1031** [comment]
Ok, thank you for the feedback. I'll update the title and description and
will take a look at SummarizedExperiment to see if the GCT class can extend
it.

**Comment by tnat1031** [comment]
hi @mtmorgan, @nturaga,

I've setup a git webhook and made some updates to the code to address the comments above, but I'm having issues getting the package to build on the Bioconductor package builder. The first submission from 8 days ago built successfully, but I received warnings from BiocCheck that I needed to update the R version requirement from 3.6.0 to 4.0. I did that, and made a few other changes to the code, but the build was being skipped as unsupported. I changed the R version requirement back to 3.6.0 but still the build is being skipped. Here is a link to the most recent build report: http://bioconductor.org/spb_reports/cmapR_buildreport_20200121201533.html

Any ideas what could be causing the problem?

Thanks a lot,
Ted

**Comment by mtmorgan** [comment]
The problem is the Dockerfile in the top level of your package. We actually plan to support Dockerfile contributions (separate from packages) and your file is tickling our implementation-in-process. Please remove the dockerfile from the master branch of the repository, or at least from the top-level directory.

**Comment by tnat1031** [comment]
Great, thanks @mtmorgan! That seems to have worked. The issue bot's message says the package was built on all 3 platforms, but I don't see the Mac results in the build report. http://bioconductor.org/spb_reports/cmapR_buildreport_20200123111812.html
Are you able to tell if indeed it was built successfully on Mac? If so, what are the next steps?

Thanks again,
Ted

**Comment by mtmorgan** [comment]
I think the message is lying to you, and it only built on Windows & Linux; we're having an ongoing problem with our Mac devel builder. @nturaga will provide a review in the next several days.

**Comment by tnat1031** [comment]
Ok, thanks for the clarification.

**Comment by tnat1031** [comment]
Hi @nturaga, just checking in on this. Have you had a chance to look at the code? Please let me know if there's anything I can do.

Thanks a lot,
Ted

**Comment by tnat1031** [comment]
Hi @nturaga, @mtmorgan, just another ping on this. Do you know when someone might be able to take a look at the code?

Thanks a lot,
Ted

**Comment by nturaga** [comment]
Hi Ted,

I'll take a look at your package this week. 

Nitesh

**Comment by tnat1031** [comment]
Great, thanks!

**Comment by nturaga** [comment]
# Review cmapR

## R CMD build

* ok

## R CMD check

* ok

## DESCRIPTION

* Not sure why the author and maintainer tags have different
  emails. It seems you are better served consolidating with the
  `Authors@R` tag and remove -Author and -Maintainer.

		Authors@R: person("First", "Last", email = "first.last@example.com",
						   role = c("aut", "cre"))

## NAMESPACE

* ok

## vignette

* ok

* You might want to consider using 'BiocStyle' package for your
  vignette. It provides standard formatting for Bioconductor packages.

  https://bioconductor.org/packages/release/bioc/html/BiocStyle.html

## man

* ok

## NEWS

* ok

## R

* Remove commented out code.

* There are places where you don't need `message()` and `paste()`
  together, this is an extra function call for no reason. 
  
```
End-User messages

message() communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.
warning() communicates unusual situations handled by your code.
stop() indicates an error condition.
cat() or print() are used only when displaying an object to the user, e.g., in a show method.
```
  
* I'd like to emphasize on a coding style Bioconductor prescribes to
  make it easier to review your
  code. http://bioconductor.org/developers/how-to/coding-style/.
  
  Please consider adopting it. It makes it easier to follow code logic
  during the review process when you have functions which span 50
  lines or so.

* In `utils.R`, please use getter and setter accessor functions, to
  classes instead of using slot accessors directly with `@`.
  
  Accessors (simple functions that return components of your object)
  rather than direct slot access (using @) help to isolate the
  implementation of your class from its interface. Generally @ should
  only be used in an accessor, all other code should use the
  accessor. The accessor does not need to be exported from the class
  if the user has no need or business accessing parts of your data
  object. Plain-old-functions (rather than generic + method) are often
  sufficient for accessors; it’s often useful to employ (consistently)
  a lightweight name mangling scheme (e.g., starting the accessor
  method name with a 2 or 3 letter acronym for your package) to avoid
  name collisions between similarly named functions in other packages.
  
  http://bioconductor.org/developers/how-to/efficient-code/

* Code file called "deprecated.R". Is this needed?

* Use the package `matrixStats` intead of writing functions like 
  `v <- apply(weighted_mat, 1, sum)`, which can be easily replaced with
  `rowSums`.

  Take a look at
    https://cran.r-project.org/web/packages/matrixStats/matrixStats.pdf

**Comment by tnat1031** [comment]
Thanks @nturaga for the feedback. I will incorporate and let you know when updates have been pushed. One question I have is about the file "deprecated.R". This contains wrappers around a small set of functions whose names were changed in order to comply with Bioconductor naming conventions, in order to maintain backward compatibility with users' code that uses the old function names. Is there a better or recommended way of doing this?

**Comment by nturaga** [comment]
That is fine then. Sounds like a reasonable thing to do.

**Comment by tnat1031** [comment]
Ok thanks

**Comment by nturaga** [comment]
Hi @tnat1031 ,

Once a review is posted the author gets 14 days to submit a response. If you are unable to respond in that time line, we can close the issue and reopen without any problems. 

If you are working on it, and require more time, please reply and confirm that you are working on it.

**Comment by tnat1031** [comment]
Hi Nitesh,

Sorry for the delay in getting back to you. Yes, I am working on addressing
the feedback in the review. If I could have a bit more time that would be
great.

Thanks very much,
Ted

**Comment by tnat1031** [comment]
Hi @nturaga,

I've merged a pull request with a few of the updates but still have a little more to do. I have a question about the use of camelCaps for variable and function names. How strictly is that enforced? I've been using snake_case almost exclusively so converting to camelCaps would require changing almost all functions and variables and would impact backwards compatibility. Is this absolutely required?

Thanks a lot,
Ted

**Comment by tnat1031** [comment]
Hi @nturaga,

I just merged another pull request with the following updates:

* updated DESCRIPTION to use `Authors@R`
* removed commented out code
* removed unneeded calls to `cat()` and `print()` within `message()`, `warning()`, etc
* created a constructor and accessor functions for the `GCT` class and removed any code directly referencing `GCT` object slots from `utils.R`
* used functions from `matrixStats` in place of calls to `apply`
* updated vignettes to use the `BiocStyle` package formatting
* updated code style to adhere to Bioconductor style guide, with the exception of converting all function and variable names to camelCaps, as this will break backwards compatibility for current users of the package. Can this conversion to camelCaps be avoided?

Thanks a lot,
Ted

**Comment by tnat1031** [comment]
Hi @nturaga,

Hope you're doing well. Can you please let me know if the last commit addressed all the issues? Thanks very much,
Ted

**Comment by lshep** [comment]
Can you please do a version bump in the DESCRIPTION file to trigger a new build report for @nturaga  to look at.

**Comment by tnat1031** [comment]
Yes, just did that, thanks

**Comment by nturaga** [comment]
Seems like you still have an error @tnat1031 . 

I'm currently reviewing the changes you made. Please fix the error.

**Comment by tnat1031** [comment]
Thanks, just did that. Hopefully new build goes well

**Comment by tnat1031** [comment]
Noticed another error. Fixing now

**Comment by tnat1031** [comment]
OK seems like the error is fixed

**Comment by tnat1031** [comment]
Hi @nturaga,

Just wondering how the review is coming. Is there anything else I need to
address? It would be great to get this package included in the upcoming
Bioconductor release if possible.

Thanks a lot,
Ted

**Comment by nturaga** [comment]
You'll need to bump the version as soon as you can. But your package has been accepted.

**Comment by tnat1031** [comment]
Ok all set, thanks so much!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tnat1031.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cmapR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cmapR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by tnat1031** [comment]
Hi @nturaga, @mtmorgan,

Thanks very much for all your help with this. I'm just checking in about when I should expect to see the cmapR package appear in the nightly devel build results and when the landing page will become active. As of this morning, it is not in the nightly build results and the landing page redirects to a page about removed packages.

Thanks a lot,
Ted

**Comment by mtmorgan** [comment]
It was added at 6:42 on Tuesday evening, after the Tuesday nightly builds had started. This means that it was included in the Wednesday builds, and would normally be reported on Thursday after about 2pm (see the header at the top of http://bioconductor.org/checkResults/3.11/bioc-LATEST/) It looks like the Wednesday builds did not report, probably because we updated R and this often means that our builds take more than 24 hours; look for your package on Friday's report.

**Comment by tnat1031** [comment]
Ok thank, you will do
