### ISSUE TITLE
corral

### ISSUE THREAD

**Issue by laurenhsu1** [Bioconductor/Contributions#1492]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/laurenhsu1/corral

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Can you please

- Expand the Description: field to an abstract-like paragraph?
- Remove the 'build products' (html documents) from the vignettes/ directory. These are created during R CMD build.

**Comment by laurenhsu1** [comment]
I just updated the description, removed the html files, and bumped the version.

**Comment by LiNk-NY** [comment]
Hi Lauren, @laurenhsu1 
There are some errors in the build. Remove any `*.Rproj` files

**Comment by laurenhsu1** [comment]
Hi Marcel, I have removed the Rproj file.

**Comment by LiNk-NY** [comment]
Can you bump the package `z` version and push? Thanks.

**Comment by aedin** [comment]
Marcel should the version number be 0.99.1 or 1.0.1?   Also can you advise on SummarizedExperiment and MAE error.

**Comment by laurenhsu1** [comment]
I already did, in these two commits:
https://github.com/laurenhsu1/corral/commit/3831c98f3f9516e9af742ec00553d521ba3bfe3b
https://github.com/laurenhsu1/corral/commit/a837a3f17e10a52867c3872292d175fb7e707b1c
Do I need to bump it again?

**Comment by LiNk-NY** [comment]
Hi Aedin, 

The version number should be `0.99.1` where `1` is the `z` version in `x.y.z`.
Version bumps are `z + 1`. 

At least for `MultiAssayExperiment`, you don't need to use `@importClassesFrom` since
you are not creating a class that inherits from `MultiAssayExperiment` (AFAICT from the
peek that I took). If you are using other functions, use the `@importFrom` for those 
functions, i.e., `experiments`, `intersectRows`.  

I think the "bump" was a version regression as you had already published `1.0`. It might be
tripping up the SPB. I can check with Lori and/or Kayla. @lshep @Kayla-Morrell 
Thanks.

**Comment by LiNk-NY** [comment]
@laurenhsu1
Please add `DuoClustering2018` to the Suggests field in the `DESCRIPTION`.

```r
> library(DuoClustering2018)
Error in library(DuoClustering2018) :
  there is no package called ‘DuoClustering2018’
```

**Comment by laurenhsu1** [comment]
Hi, it is there: https://github.com/laurenhsu1/corral/blob/master/DESCRIPTION

**Comment by LiNk-NY** [comment]
Hi Lauren, @laurenhsu1 
Sorry! It's not installed in my system. 

Can you please use 2 or 4 spaces in the DESCRIPTION file and
add indentation to the `Description: ` field?

We usually download packages like this: 
```r
> BiocManager::install("laurenhsu1/corral", dependencies = TRUE)
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.0 beta (2020-04-14
  r78225)
Installing github package(s) 'laurenhsu1/corral'
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'similar to principal ...' is malformed!
```
but currently, I'm getting an error. It is due to the formatting in the `DESCRIPTION` file. Thanks!

**Comment by aedin** [comment]
Hi Marcel
I tested BiocManager::install("laurenhsu1/corral", dependencies = TRUE) on my Mac and it worked ok.  Hopefully, it works for you now also
Thanks
A

**Comment by laurenhsu1** [comment]
Hi Marcel @LiNk-NY , 

In the latest build report (https://bioconductor.org/spb_reports/corral_buildreport_20200502002751.html#tokay2_check_anchor), this is the only error left:

* ERROR: Packages providing 1 object(s) used in this package should
      be imported in the NAMESPACE file, otherwise packages importing
      this package may fail.
    
      package::object in function()
        MultiAssayExperiment::MultiAssayExperiment in corralm()

I added it back in, yet it is still giving this error. I also got a different error about it when I didn't include it in the roxygen/Namespace file. Do you have suggestions about what how I should resolve this?

Thanks

**Comment by LiNk-NY** [comment]
Hi Lauren @laurenhsu1 & Aedin @aedin 

It seems to be a weird bug in `BiocCheck` but there are a few typos on this line: 
https://github.com/laurenhsu1/corral/blob/35801fb119d72091bb8df36c1001797aa8958f89/R/corralm.R#L118 where `:` should be `::`. 

Once this is fixed, it will give you a note: 
```
* Checking to see if we understand object initialization...
    * NOTE: Consider clarifying how 4 object(s) are initialized. Maybe
      they are part of a data set loaded with data(), or perhaps part
      of an object referenced in with() or within().
    function (object)
      corral (is)
      corral_preproc (is)
      corralm (is)
      get_weights (is)
```

**Comment by laurenhsu1** [comment]
Thanks Marcel @LiNk-NY, I just fixed that line with the single colons

**Comment by LiNk-NY** [comment]
Hi Lauren, @laurenhsu1 
There are still a couple of warnings to resolve: 
```
* checking package subdirectories ... WARNING
Subdirectory 'inst/doc' contains invalid file names:
  '1-corral.Rmd' '2-corralm.Rmd' '1-corral.html' '2-corralm.html'
Please remove or rename the files.
See section 'Package subdirectories' in the 'Writing R Extensions'
manual.
```
I guess it means that the `-` in the file name is not allowed. 

These are relatively quick fixes: 

```
* checking S3 generic/method consistency ... WARNING
print:
  function(x, ...)
print.corral:
  function(inp)

print:
  function(x, ...)
print.corralm:
  function(inp)

See section 'Generic functions and methods' in the 'Writing R
Extensions' manual.
```

```
* checking R code for possible problems ... [41s] NOTE
corral: no visible global function definition for 'is'
corral_preproc: no visible global function definition for 'is'
corralm: no visible global function definition for 'is'
get_weights: no visible global function definition for 'is'
Undefined global functions or variables:
  is
Consider adding
  importFrom("methods", "is")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
contains 'methods').
```

There are couple of other notes in the report as well. Particularly the 100 character
note for PDF vignettes (?) and the 'unstated dependencies' note that should be resolved. 

I will continue with the review of the package shortly. 
Best,
Marcel

**Comment by laurenhsu1** [comment]
Hi Marcel @LiNk-NY,
I just pushed a version that addresses these, but now addressing this one:

```
* checking R code for possible problems ... [41s] NOTE
corral: no visible global function definition for 'is'
corral_preproc: no visible global function definition for 'is'
corralm: no visible global function definition for 'is'
get_weights: no visible global function definition for 'is'
Undefined global functions or variables:
  is
Consider adding
  importFrom("methods", "is")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
contains 'methods').
```
from the previous version (https://bioconductor.org/spb_reports/corral_buildreport_20200504112016.html) results in an error 
creates a new error:
```
* checking package dependencies ... ERROR
Namespace dependency not required: 'methods'

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
* DONE

Status: 1 ERROR
```
in the most recent one (https://bioconductor.org/spb_reports/corral_buildreport_20200504145357.html)

Do you have any suggestions about how to resolve this?

Thanks

**Comment by LiNk-NY** [comment]
Hi Lauren, @laurenhsu1 

Thank you for your submission. 
Please see the review below. 
If you have any questions, feel free to post them as comments below.

Best,
Marcel

---

# corral #1492

## DESCRIPTION

* It looks good.
* Minor: Use `Authors@R` instead of `Author` and `Maintainer` fields if you'd
like to add your ORCID ID and authorship details.
* Consider using BiocStyle for the vignettes and adding it to `Suggests`

## NAMESPACE

* Looks good.
* It seems that you are using an S3 class.

## vignettes/

* Please keep the text within the 80 column width limit. It's hard to read
and maintain when the text goes off the page.
* Perhaps it would be better for users to expect and get a consistent output
despite the input (e.g., `SingleCellExperiment` or a derivative)
* It would be good to have an easy way to convert a list of
`SingleCellExperiment`s or similar into a `MultiAssayExperiment` object that
uses the `colData` in one motion. The code in the 4th chunk of in the
alignment vignette would be avoided. You could then do `assays` to get a list
of matrices.

## R

* Use `match.arg` within the function instead of `c("irl", "svd")[1]` for
vector default arguments (`corralm_matlist`)
* Avoid using `'false'` strings. Use `FALSE`.
* Shorten error messages where possible.
* Re-using an S4 class has added benefits of a show method. Perhaps use a
`List` derivative, `ExperimentList`, etc.
* Functions that are not intended to be called directly should be internal.
Use a `@keywords internal` tag.
* Avoid using numeric indices where possible and use more robust names.
* When creating a sequence, avoid using `1:n` syntax, use the more robust
`seq_along(x)` or `seq_len(nrow(x))`.
* The `na2zero` implementation should be endomorphic and vectorized so that
it works on a matrix and returns a matrix rather than having the user enter,
`apply(x, c(1,2), na2zero)`.
* If I understand the process correctly, the `add_embeddings*` function
adds the results to the list of SCE objects. Perhaps it supports the idea
that the package could use a unified representation of SCEs as a `List` /
`ExperimentList`.
* Minor: It would be nice to see a single function handles both single and
multiple tables and returns a consistent output.

## test

* Optional: Add more tests to increase the robustness of the package.

**Comment by aedin** [comment]
Thanks 
Lauren has her thesis defense on a Thursday so probably won’t review this until after that. 

It would be great to have a quick discussion (maybe slack or zoom??) on how best to interrelate corral with sce and mae and other bioc classes. 

Aedin

**Comment by LiNk-NY** [comment]
Hi Aedin, @aedin 
I can meet today via Slack call.
Let me know what time works for you. 
Best,
Marcel

**Comment by laurenhsu1** [comment]
Hi Marcel @LiNk-NY,
Thanks for your review, now in the process of making updates to the package. Could we schedule the slack call Aedin @aedin suggested at some point tomorrow or Thursday? We are both available in the afternoons those days, please let us know if there's a time that works for you too.
Best,
Lauren

**Comment by LiNk-NY** [comment]
Hi Lauren @laurenhsu1 and Aedin @aedin, 
What times are you available?
I can do today and tomorrow after 4 PM EDT (GMT-4) or 
12 - 1 PM tomorrow. 
Best,
Marcel

**Comment by laurenhsu1** [comment]
Hi Marcel @LiNk-NY,
Let's meet today at 4p eastern on the bioconductor slack.
Thanks,
Lauren

**Comment by LiNk-NY** [comment]
:ok_hand: see you then!

**Comment by laurenhsu1** [comment]
Hi Marcel @LiNk-NY,

I’ve pushed a version of the package that appears to pass the build (the warning is because it took > 20min to build, but I didn't substantially change from before so I am guessing this is some sort of system error? the one before that didn't get posted by bioc-issue-bot and appears to have some issues with loading the DuoClustering dataset which self-resolved when I just bumped version http://staging.bioconductor.org:8000/job/12422/). 

It includes the rest of the updates to the package, including adding a visual explainer of the input/output formats for the methods in the respective vignettes. In the alignment vignette I also added the MAE lines that you added as commented out with a brief note about the devel branch, and will plan to uncomment them after the new version of MAE is released (for the time being, I get a build error when I leave them there.)

Per the conversation in slack on SCE list, I have not made a new class. I did add checks in the functions to ensure all elements of list are consistent. There is also a way to toggle into having the full output using the fullout argument in either method.

Let me know what the next steps are.

Thanks,
Lauren

**Comment by LiNk-NY** [comment]
Hi Lauren, @laurenhsu1 

Thank you for making those changes.

Once the package is accepted, it will go into the devel branch. You don't have to mention that you are using Bioconductor devel because your initial users will all be using Bioconductor devel. 
You can uncomment the code since it should now work in the devel branch (the change in `MultiAssayExperiment` has propagated).

Regarding the DuoClustering dataset, it may have been an intermittent connection issue. 

Thank you.

**Comment by laurenhsu1** [comment]
Hi Marcel @LiNk-NY ,
I'm still getting the same error:
`Quitting from lines 81-85 (corralm_alignment.Rmd) 
Error: processing vignette 'corralm_alignment.Rmd' failed with diagnostics:
no method or default for coercing "list" to "MultiAssayExperiment"
--- failed re-building corralm_alignment.Rmd
`
(as in this build report: https://bioconductor.org/spb_reports/corral_buildreport_20200520145233.html)

**Comment by LiNk-NY** [comment]
Hi Lauren, @laurenhsu1 

This is strange. It looks like the SPB is using Bioconductor 3.11. 

Lori @lshep, Kayla @Kayla-Morrell : 
Shouldn't it be using Bioconductor 3.12? 

I've tried to replicate this locally with Bioc-devel and I get an error on different lines.
```
Rdev CMD build corral
--- re-building ‘corralm_alignment.Rmd’ using rmarkdown
Loading required package: magrittr
Loading required package: tibble
Quitting from lines 115-116 (corralm_alignment.Rmd) 
Error: processing vignette 'corralm_alignment.Rmd' failed with diagnostics:
subscript contains invalid names
--- failed re-building ‘corralm_alignment.Rmd’
```
When I Stangle, I get: 
```
Rdev CMD Stangle corral/vignettes/corralm_alignment.Rmd
Output file:  corralm_alignment.R
mr148@mr148-Z68MA-D2H-B3 ~/bioconductor $ Rdev -e "source('corralm_alignment.R')"
Error: subscript contains invalid names
In addition: Warning message:
In load(data_path1) : invalid or incomplete compressed data
Execution halted
```

I think I have the latest packages:

```r
> BiocManager::valid()

* sessionInfo()

R version 4.0.0 Patched (2020-05-16 r78478)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_4.0.0      tools_4.0.0        

Bioconductor version '3.12'

  * 1 packages out-of-date
  * 0 packages too new

create a valid installation with

  BiocManager::install("RcisTarget", update = TRUE, ask = FALSE)

more details: BiocManager::valid()$too_new, BiocManager::valid()$out_of_date

Warning message:
1 packages out-of-date; 0 packages too new 
```

**Comment by laurenhsu1** [comment]
Hi Marcel @LiNk-NY,
the error you're getting locally is because I didn't update the rest of the code based on what MAE does with colData names, I'll fix that.

**Comment by laurenhsu1** [comment]
Hi Marcel @LiNk-NY ,

What is the name of the colData attribute that using `as` on a list of SCEs will put the names of the experiments? From looking at the MAE github, it looks like it is going into an attribute called 'experiment_name', but the latest build is giving me an error on that (http://staging.bioconductor.org:8000/job/12475/ --> line 115 is where the name of the experiment is first referenced)

Thanks,
Lauren

**Comment by LiNk-NY** [comment]
Hi Lauren, @laurenhsu1 
Apologies for the delay in getting back to you. I've had a look at the code. 
I only add 'experiment_name' to the `colData` of the MultiAssayExperiment
and not the individual elements. 
If you'd like to extract a single experiment with the `colData` we have a helper
called `getWithColData` but it only works on the original `MultiAssayExperiment`
object. 

```r
scmix_mae <- as(scmix_dat,'MultiAssayExperiment')
scmix_mae <- intersectRows(scmix_mae)
scmix_sce <- SingleCellExperiment::cbind(
    getWithColData(scmix_mae, 1L),
    getWithColData(scmix_mae, 2L),
    getWithColData(scmix_mae, 3L)
)
```

**Comment by laurenhsu1** [comment]
Hi Marcel @LiNk-NY ,
Thanks for clarifying. I have updated the package, and it has now built without errors. 

It was odd though, because on the most recent, version 31 (http://staging.bioconductor.org:8000/job/12490/), there were no errors. 
On version 30 (http://staging.bioconductor.org:8000/job/12489/), there was a build error on macOS related to importing MultiAssayExperiment. 
On version 29 (http://staging.bioconductor.org:8000/job/12488/) it passed on macOS but failed linux and windows

However, the only change between v 30 and 31 was a version bump, and between v 29 and 30 was a single change from ::: to :: (unrelated to MultiAssayExperiment)

Is this normal for the check to vary this much between runs?

Thanks,
Lauren

**Comment by LiNk-NY** [comment]
Hi Lauren, @laurenhsu1 

It is not normal. Lori @lshep has been working hard on updating the SPB
to use Bioc devel and this likely has caused some instability in the test results. 
Thanks for making those changes. Your package has been accepted :tada: 

Best regards,
Marcel

**Comment by lshep** [comment]
Yes sorry for any confusion.  We were running updates on the SPB and it may take a few days to settle.  Glad your package is accepted. Welcome to Bioconductor.

**Comment by laurenhsu1** [comment]
Thanks @LiNk-NY and @lshep!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/laurenhsu1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("corral")`. The package 'landing page' will be created at

https://bioconductor.org/packages/corral

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
