### ISSUE TITLE
BloodGen3Module

### ISSUE THREAD

**Issue by Drinchai** [Bioconductor/Contributions#1745]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Drinchai/BloodGen3Module

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by lshep** [comment]
Thank you for your submission to Bioconductor. Please see my comments below to address: 

**BUILD REPORT**

- [ ] Please fix coding NOTES
- [ ] Please have a more detailed description section in DESCRIPTION. Think of the Description as an abstract


**README**

- [ ] Please also include Bioconductor installation instructions.  You can keep the github but advertise it as devel with stable being through Bioconductor `BiocManager::install()` 

**DESCRIPTION**

- [ ] Please remove `LazyData: true` we have rarely found this useful and it can  actually slow down installation

- [ ] data-raw. data-raw is not included in the package distribution. For this reason we encourage scripts to be in an inst/script directory instead of data-raw so that users could reference directly from the package. The scripts you currently have in data-raw should not be included in the package. They only reference the data that is exposed to the user already through the data directory. Please remove this folder and scripts. If the data is meant to only be used internally they should not be in a data directory. See  the chapter on data https://r-pkgs.org/data.html


**Data directory / man pages for data**

- [ ] Please expand the man page documentation for the data objects. Please include source references or more information on how the data was generated. Please include more detail on the structures as well. For example: data.frame with 6 variables but then you only list 2?

**NEWS**

- [ ] Do not include a blank NEWS file. Please include entries or remove. Many often use something along the lines as the placeholder, first entry.

```
Changes in version 0.99.23
------------------------

  - submission to Bioconductor 

```
**TEST - inst/unitTests**

- [ ] We would recommend using either testthat or RUnit but not a mixture of both.


**vignettes**

- [ ] Please remove the html version of the vignette. The vignette should be generated automatically through the build/check process.

- [ ] We would hightly recommend having a more informated title that includes the package name. Generic titles like vignette.Rmd or introduction.Rmd run the risk of having conflicting names with other packages and a user that does
  
  ```
  vignette("introduction")
  ```
  depending on the other packages loaded in the namespace may or may not get the right vignette for your package. You can see the warning about matching more than one, even though yours does acutally get used in this case.
  
  ```
  > vignette("introduction")
  starting httpd help server ... done	
  Warning message:
  vignette 'introduction' found more than once,
  using the one found in '/home/shepherd/R-Libraries/4.1-Bioc3.13/BloodGen3Module/doc' 

  ```


- [ ] If your package are properly indicated in the DESCRIPTION and the NAMESPACE, Packages_installation.Rmd is irrelevant and should be removed. Furthermore `BiocManager::install` installs package from both CRAN and Bioconductor so having the two seperate functions is unnecessary. Bioconductor::install uses both Bioconductor and CRAN as default repositories. This vignette really should be deleted but if you insist on keeping it all coding blocks should have an `eval=FALSE`. Vignettes should never automatically try to download/install packages on the build system/users system without them knowing.

_introduction_ 

- [ ] We recommend BiocStyles for vignette style but this is an optional change

- [ ] If you are going to hid the library call to knitr you probably should repress the output of the code block as well to avoid showing the following at the top
  
  ```
  ## Loading required package: knitr
  ```

- [ ] Include Bioconductor installation instructions

- [ ] We do not allow sample data to be stored on github. It should be included with the package or if the data is too large then the data should be made into an experimenthub data package. The package whenever possible is encourage to use a small real subset of data.

- [ ] Looking at your sample data for data.matrix, The package should be able to also use SummarizedExperiment Bioconductor class for input. This is a standard well used Bioconductor class for any rectangular feature x sample data. A SummarizedExperiment will have the data.matrix and sample_ann information stored without one class object.  

- [ ] For Fingerprint grid visualization, please use a `tempdir()\tempfile()`  for filename argument.

- [ ] Individual single sample analysis should have an option to take in and return SummarizedExperiment object as well. 


**R code - man docs**

- [ ] All functions should take a SummarizedExperiment as an argument in addition to regular matricies. Most Bioconductor related functions that could utilize this package would have data in a SummarizedExperiment object.

- [ ] We don't encourage the repeat of large code blocks. For example lines 49-73 of Groupcomparison.R is the exact same as 53-77 of Groupcomparisonlimma.R. similarly with the end of the functions from calculate fold change to basically the end. Making only the middle section unique to the functions. It is almost worth just having a signle function that would perform the unique steps based on an additional argument to indicate if its limma or not. If you keep the two seperate functions, the large sections of repeated code should be seperated out into functions that are called by each. ie. a helper/internal only function `.fold_change()`, `.percentage_of_response()`, etc .... smaller/internal functions also make it easier to write smaller, more focused unit tests.
  
Now also looking at Individualcomparison.R it is also largely repeated code.

- [ ] Similar comment as above for all the repeated code in the plotting functions. It seems like this really could be cleaned up into an analysis function and a plotting function that is exported to the user.


Please address the above issues. When ready please push a version bump to git.bioconductor.org to trigger a new build of the package and comment back here commenting on changes/updates in response to above. 
Thank you 
Cheers!

**Comment by lshep** [comment]
Just wanted to check in to see if you would be following up with the review?

**Comment by Drinchai** [comment]
Thank Ishep for your review! Yes, I am working on all comments and will have an update soon.

**Comment by lshep** [comment]
Excellent. thanks for the update

**Comment by Drinchai** [comment]
AdditionalPackage: https://github.com/Drinchai/GSE13015

**Comment by mtmorgan** [comment]
It looks like GSE13015 is an 'ExperimentHub' package; it should have BiocViews terms selected from the 'Experiment Data' hierarchy http://bioconductor.org/packages/devel/BiocViews.html#___ExperimentData tag @mtmorgan in a comment when you have made this change

**Comment by Drinchai** [comment]
@mtmorgan , Thank you for your review. Yes, I would like to create an "ExperimentHub" package of data for testing "BloodGen3Module" Package.  I have just added "ExperimentData" to bioViews.

**Comment by lshep** [comment]
In the meantime while we are waiting for approval to build, I'm assuming you were planning on using the default Bioconductor S3 bucket to host the data? If so can you send an email to hubs at bioconductor.org  to request the access credentials.  We can start working on getting the data in the database so you can download from the hub.

**Comment by lshep** [comment]
Please correct the ERROR in the build report and please see above [comment](https://github.com/Bioconductor/Contributions/issues/1745#issuecomment-756762953)  ,we been experiencing some interrputions using the hubs email so please also include lori.shepherd at roswellpark.org on the request for access.  Cheers

**Comment by Drinchai** [comment]
@lshep, I have corrected the error from build report but I am not able to push it to bioconductor:

Darawans:GSE13015 darawanrinchai$  git add DESCRIPTION 
Darawans:GSE13015 darawanrinchai$ git commit -m "Update version"
[main ca96cf6] Update version
 1 file changed, 1 insertion(+), 1 deletion(-)
Darawans:GSE13015 darawanrinchai$ git push upstream master 
error: src refspec master does not match any
error: failed to push some refs to 'git@git.bioconductor.org:packages/GSE13015.git'

**Comment by lshep** [comment]
Could you try doing a `git fetch -a`  before doing the `git push upstream master`

**Comment by lshep** [comment]
I'll start working on the review of GSE13015 -- could you start updating the BloodGen3Module to use the ExperimentHub data accordingly and push off a new build and let me know when that is ready for a re-review

**Comment by Drinchai** [comment]
@lshep Sorry for my late response. We are waiting to hear back from reviewers after revised submission of this R package manuscript. I prepared all documents as your comments and will push to Bioconductor after we hear back from reviewer. Is that, OK?

**Comment by lshep** [comment]
Sure. No problem.  I'll still continue with the GSE13015  review in the meantime.  Cheers

**Comment by lshep** [comment]
I've looked at GSE13015 awhile.  Please see the following concerns that should be addressed: 

**DESCRIPTION/License**

- [ ] It seems like you included the MIT license but reference Artistic-2.0 in
  the description. Please choose one and be consisent. If you choose
  Artistic-2.0 the license is distributed with R and does not need to be
  included as a seperate file.

- [ ] Add `ExperimemtHub` to the biocViews in the Description.


**Data/Hub/Vignette**

- [ ] It doesn't look like the data was ever added to the ExperimentHub / AWS S3
  bucket?  Did we assist you with this request?  You will need to upload your
  data to the S3 bucket as described in [Creating a Hub
  Package](https://bioconductor.org/packages/devel/bioc/vignettes/AnnotationHub/inst/doc/CreateAHubPackage.html#uploading-data-to-s3).
  I will email you credentials shortly to the email in the DESCRIPTION file.
  Once the data is uploaded, I can officially add the entry to the experimenthub
  database for access in your vignette.

- [ ] There is an ERROR in your vignette code even if the data was available.  

```
dat = ExperimentHub()
query(dat , "GSE13015")
data_matrix <- dat[[1]]
```

The last part is wrong as it will grab the first entry of the entire
experimenthub. You would want to grab the first entry of the query.

```
dat = ExperimentHub()
res = query(dat , "GSE13015")
data_matrix <- res[[1]]
```


**extdata/metadata.csv**

- [ ] You'll want to have some distiction between the title and description for
  each entry or users will not be able to know the difference between what they
  are grabbing. (ie. clear one is as it seems an expressionset and one a
  summarizedexperiment) You can see why if you navigate to the web interface
  like
  https://experimenthub.bioconductor.org/rdataclass/SummarizedExperiment

- [ ] The BiocVersion should be the current devel version 3.13 as this will be
  the hub release the resource will be available.

- [ ] Currently the RDataPath's are the same.  You will want different paths to
  the two different objects and the top level directory should be your package
  name:

Current:
```
GSE13015_GPL6106/GSE13015_GPL6106.Rda
GSE13015_GPL6106/GSE13015_GPL6106.Rda
```
So you'll want one file with the summarizedexperiment and one file for the
expression set if you are going to provide both versions of the object. Perhaps:

```
GSE13015/GSE13015_GPL6106_ExpressionSet.Rda
GSE13015/GSE13015_GPL6106_SummarizedExperiment.Rda
```

Let me know if you have any questions or concerns. 
Cheers,

**Comment by lshep** [comment]
Is there a progress update at all for the changes?

**Comment by Drinchai** [comment]
@lshep BloodGen3Module is now accepted on Bioinformatics!
I just edited information of GSE13015 as your comments, also uploaded file to Experimenthub/GSE13015.
I also pushed the updated version to Bioconductor, it give the error report as failed to create vignettes, is this should be skipped for creating vignettes, right?

**Comment by lshep** [comment]
A package should always have a runnable vignette.  I will work on getting the data into the hub for access either today or tomorrow.

**Comment by lshep** [comment]
There are some issues in the metadata.csv file that need to be corrected in order for me to add the GSE13015 data to the hub.  
Please delete the first entry (row 2)  in the metadata.csv file that refers to an ExpressionSet object.  You have uploaded only one file and that file is in the form of a SummarizedExperiment. 
Please update the BiocVersion to be  3.13.  This should be the Bioconductor version your package is being released under. 
The RDataPath should be the path location of the data you uploaded. 
GSE13015/GSE13015_GPL6106_SummarizedExperiment.Rda
Also SourceVersion cannot contain commas  so please use `Jul 1 2009` instead of `Jul 1, 2009`. 

Thank you! 

Please let me know when the metdata.csv file is updated and pushed to git and I will try to add the data again.

**Comment by Drinchai** [comment]
@lshep Thank you so much for your comment. I have updated metadata.csv file and other points as your comments, also pushed to git.

**Comment by lshep** [comment]
The data has been added to the hubs of the devel version of Bioconductor
```
> hub = ExperimentHub()
snapshotDate(): 2021-03-23
> query(hub, "GSE13015")
ExperimentHub with 1 record
# snapshotDate(): 2021-03-23
# names(): EH5429
# package(): GSE13015
# $dataprovider: GEO
# $species: Homo sapiens
# $rdataclass: SummarizedExperiment
# $rdatadateadded: 2021-03-23
# $title: GSE13015_GPL6106_Microaray_SEPSIS
# $description: Microarray expression datafor 67 septicemic patients, repres...
# $taxonomyid: 9606
# $genome: hg19
# $sourcetype: tar.gz
# $sourceurl: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE13015
# $sourcesize: NA
# $tags: c("GEO", "MicroarrayData") 
# retrieve record with 'object[["EH5429"]]' 
 temp = hub[["EH5429"]]
```

Please update vignettes/examples/tests to use the data accessed from the hubs.  When you are ready please leave a comment there that you are ready for a re-review of the packages.  
Cheers

**Comment by Drinchai** [comment]
I am not get the data to test the scrip.

> library(ExperimentHub)
> dat = ExperimentHub()
snapshotDate(): 2020-10-27
> res = query(dat , "GSE13015")
> res
ExperimentHub with 0 records
# snapshotDate(): 2020-10-27
Could you please advise?

**Comment by lshep** [comment]
You have to be using R devel ( R 4.1)  and Bioconductor version 3.13 in order to see the data.

**Comment by lshep** [comment]
I'm going to kick off a new build for BloodGen3Module to see if some of the errors clean up as some were package availability -- you should have a new build report shortly

**Comment by Drinchai** [comment]
@lshep Thank you so much for you review, please see below.

All changes/updates in response to below.
However:  there is a warning that I am not able to find the solution;
Warning messages:
1: replacing previous import ‘SummarizedExperiment::rowRanges’ by ‘matrixStats::rowRanges’ when loading ‘BloodGen3Module’ 
2: replacing previous import ‘SummarizedExperiment::start’ by ‘stats::start’ when loading ‘BloodGen3Module’ 
3: replacing previous import ‘SummarizedExperiment::end’ by ‘stats::end’ when loading ‘BloodGen3Module’
Could you please advise?
Thank you very much!
Darawan

#### All changes/updates
BUILD REPORT
•	 Please fix coding NOTES
•	 Please have a more detailed description section in DESCRIPTION. Think of the Description as an abstract
>> These have been updated.

README
•	 Please also include Bioconductor installation instructions. You can keep the github but advertise it as devel with stable being through Bioconductor BiocManager::install()
>> To avoid the error in build report. This script will be add in the latest version before accepting.
#Installation from Bioconductor: 
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install("BloodGen3Module")

DESCRIPTION
•	 Please remove LazyData: true we have rarely found this useful and it can actually slow down installation
>> I have data that need for functions “Gen3_ann”, “Modulelist_Gen3” and “color” when I removed this line. These data don’t load to the package and functions doesn’t work. Could you advise?

•	 data-raw. data-raw is not included in the package distribution. For this reason we encourage scripts to be in an inst/script directory instead of data-raw so that users could reference directly from the package. The scripts you currently have in data-raw should not be included in the package. They only reference the data that is exposed to the user already through the data directory. Please remove this folder and scripts. If the data is meant to only be used internally they should not be in a data directory. See the chapter on data https://r-pkgs.org/data.html
>> I did try to move the scripts in inst/script as reviewer suggestion but it affects the data that required for functions as above. 

Data directory / man pages for data
•	 Please expand the man page documentation for the data objects. Please include source references or more information on how the data was generated. Please include more detail on the structures as well. For example: data.frame with 6 variables but then you only list 2?
>> Information have been updated.

NEWS
•	 Do not include a blank NEWS file. Please include entries or remove. Many often use something along the lines as the placeholder, first entry.
Changes in version 0.99.36
------------------------
  - submission to Bioconductor 

>> NEWs information was added into Package

TEST - inst/unitTests
•	 We would recommend using either testthat or RUnit but not a mixture of both.
>> Runit was removed

vignettes
•	 Please remove the html version of the vignette. The vignette should be generated automatically through the build/check process.
>> html file was removed
•	 We would hightly recommend having a more informated title that includes the package name. Generic titles like vignette.Rmd or introduction.Rmd run the risk of having conflicting names with other packages and a user that does
•	vignette("introduction")
depending on the other packages loaded in the namespace may or may not get the right vignette for your package. You can see the warning about matching more than one, even though yours does acutally get used in this case.
> vignette("introduction")
starting httpd help server ... done	
Warning message:
vignette 'introduction' found more than once,
using the one found in '/home/shepherd/R-Libraries/4.1-Bioc3.13/BloodGen3Module/doc'

>> now file has been changing to BloodGen3Module.Rmd

•	 If your package are properly indicated in the DESCRIPTION and the NAMESPACE, Packages_installation.Rmd is irrelevant and should be removed. Furthermore BiocManager::install installs package from both CRAN and Bioconductor so having the two seperate functions is unnecessary. Bioconductor::install uses both Bioconductor and CRAN as default repositories. This vignette really should be deleted but if you insist on keeping it all coding blocks should have an eval=FALSE. Vignettes should never automatically try to download/install packages on the build system/users system without them knowing.
>> The file was removed.
introduction
•	 We recommend BiocStyles for vignette style but this is an optional change
•	 If you are going to hid the library call to knitr you probably should repress the output of the code block as well to avoid showing the following at the top
•	## Loading required package: knitr
>> The Introduction has been updated.

•	 Include Bioconductor installation instructions
•	 We do not allow sample data to be stored on github. It should be included with the package or if the data is too large then the data should be made into an experimenthub data package. The package whenever possible is encourage to use a small real subset of data.
•	 Looking at your sample data for data.matrix, The package should be able to also use SummarizedExperiment Bioconductor class for input. This is a standard well used Bioconductor class for any rectangular feature x sample data. A SummarizedExperiment will have the data.matrix and sample_ann information stored without one class object.
>> Now the data was added to Experimenthub GSE13015

•	 For Fingerprint grid visualization, please use a tempdir()\tempfile() for filename argument.
>> tempfile() was added into filename argument 

•	 Individual single sample analysis should have an option to take in and return SummarizedExperiment object as well.
>> Now the output is exported as SummarizedExperiment object
R code - man docs
•	 All functions should take a SummarizedExperiment as an argument in addition to regular matricies. Most Bioconductor related functions that could utilize this package would have data in a SummarizedExperiment object.
>> SummarizedExperiment was added as an argument in “Individualcomparison” function
•	 We don't encourage the repeat of large code blocks. For example lines 49-73 of Groupcomparison.R is the exact same as 53-77 of Groupcomparisonlimma.R. similarly with the end of the functions from calculate fold change to basically the end. Making only the middle section unique to the functions. It is almost worth just having a signle function that would perform the unique steps based on an additional argument to indicate if its limma or not. If you keep the two seperate functions, the large sections of repeated code should be seperated out into functions that are called by each. ie. a helper/internal only function .fold_change(), .percentage_of_response(), etc .... smaller/internal functions also make it easier to write smaller, more focused unit tests.
Now also looking at Individualcomparison.R it is also largely repeated code.
•	 Similar comment as above for all the repeated code in the plotting functions. It seems like this really could be cleaned up into an analysis function and a plotting function that is exported to the user.
>> >> fold_change was added, and scripts were updated

Please address the above issues. When ready please push a version bump to git.bioconductor.org to trigger a new build of the package and comment back here commenting on changes/updates in response to above.

**Comment by lshep** [comment]
Thank you for your updates.  Please see the comments below: 

**GSE13015**

 - [x] OK


**BloodGen3Module**

_General_

- [ ] I think the Warnings concerning imports have to do with conflicting
  functions of the same name in each package. I think if in the namespace and
  code you specified which you were using by importFrom()  and in the code
  package::rowRanges  etc they would go away (but only guessing not entirely
  sure)


_README_

 - [ ] Please also include Bioconductor installation instructions. You can keep
 the github but advertise it as devel with stable being through Bioconductor
 BiocManager::install()


_DESCRIPTION/data-raw_

- [ ] I believe data needed internally for functions to run should be in
  sysdata.rda
  See [Internal data](https://r-pkgs.org/data.html#data-sysdata)
  Side note:  when I get pull it looks like it was renamed to `dara-raw`
  

_Data_

- [ ] Please include source information for the data or how the data was
  generated. For the data in the `data/` directory it should be included in the
  man files.


_Vignette_

- [ ] Use Bioconductor installation instructions. For both Bioconductor and
  github installation instructions please set to `eval=FALSE`

- [ ] The Groupcomparison/Groupcomparisonlimma should also be able to directly
  take in the SummarizedExperiment, not just the Individualcomparison
  function. If you made the change to Individualcomparison to directly take a
  SummarizedExpeirment class it would be good to show this option in the
  vignette. If doesn't look like you could input a summarizedexperiment only
  export as one (which is good). For input I would recommend having data.matrix
  take a matrix or summarizedexperiment, check the class with `is()` and if it
  is a summarizedexpeirment parse out the matricies. sample_info could default
  to Null and check that if a summarizedexpeirment was not given that it has to
  be specified.


Please address the above issues and when ready do a version bump to trigger a new build and request a re-review commenting on the above concerns.  

Cheers.

**Comment by lshep** [comment]
Please keep me mind the deadline to add packages for the 3.13 release is under a week away.  After this date packages accepted will remain in Bioconductor devel and released under 3.14.

**Comment by Drinchai** [comment]
@lshep  Thank you so much for your reminder. I will try to get it before the deadline.
 Please see below for my response. Now the internal data and functions were updated as your suggestions. 

BloodGen3module

- [ ] General
I think the Warnings concerning imports have to do with conflicting
functions of the same name in each package. I think if in the namespace and
code you specified which you were using by importFrom() and in the code
package::rowRanges etc they would go away (but only guessing not entirely
sure)

>> I have tried  multiple ways by adding/editing namespace;  importFrom(SummarizedExperiment,rowRanges) or importFrom(matrixStats,rowRanges) but the warning is still there when I run BiocCheck("BloodGen3Module")

- [ ] README

 Please also include Bioconductor installation instructions. You can keep
the github but advertise it as devel with stable being through Bioconductor
BiocManager::install()
DESCRIPTION/data-raw
>> updated as suggestions

 I believe data needed internally for functions to run should be in
sysdata.rda
See Internal data
Side note: when I get pull it looks like it was renamed to dara-raw
>> Thank you for your suggestions, now the data is in sysdata.rda

- [ ] Data

 Please include source information for the data or how the data was
generated. For the data in the data/ directory it should be included in the
man files.
>> Informations were added to man files.

- [ ] Vignette

 Use Bioconductor installation instructions. For both Bioconductor and
github installation instructions please set to eval=FALSE
>> edited as reviewer suggestions

 The Groupcomparison/Groupcomparisonlimma should also be able to directly
take in the SummarizedExperiment, not just the Individualcomparison
function. If you made the change to Individualcomparison to directly take a
SummarizedExpeirment class it would be good to show this option in the
vignette. If doesn't look like you could input a summarizedexperiment only
export as one (which is good). For input I would recommend having data.matrix
take a matrix or summarizedexperiment, check the class with is() and if it
is a summarizedexpeirment parse out the matricies. sample_info could default
to Null and check that if a summarizedexpeirment was not given that it has to
be specified.

>> edited as reviewer suggestions, all functions are able to get summarizedexperiment as output.

**Comment by lshep** [comment]
I tested R CMD build and R CMD check locally on my system and do not encounter an ERROR.  I will accept and assume this is some intermittent ERROR. if we see it consistently on the daily builder we can revisit trying to debug.  

Thank you for making the relevant changes and welcome to Bioconductor.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Drinchai.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BloodGen3Module")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BloodGen3Module

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Drinchai.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GSE13015")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GSE13015

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
