### ISSUE TITLE
EWCE

### ISSUE THREAD

**Issue by Al-Murphy** [Bioconductor/Contributions#1904]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/neurogenomics/ewceData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by Al-Murphy** [comment]
The error seems to be down to a ggplot object part of the data object ctd (ctd[[1]]$plotting$ggdendro_vertical) I can't seem to reproduce this error locally and looking online the only related issue seems to be here: https://stackoverflow.com/questions/60187844/error-in-getas-characterfun-mode-function-envir-envir-object-guid. @lshep have you encountered an issue like this before? Sorry it's hard to correct since it isn't failing locally.

The error:
`[[1]]$plotting$ggdendro_vertical
Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'guide_none' of mode 'function' was not found
Calls: <Anonymous> ... lapply -> FUN -> f -> lapply -> FUN -> match.fun -> get
Execution halted`

**Comment by lshep** [comment]
Please note you are also getting ERROR's for not being signed up for the mailing list and having some files that should not be git tracked. 
I am able to reproduce this locally,  Please make sure you are testing with R-devel (R4.1) and Bioconductor 3.13.

**Comment by Al-Murphy** [comment]
Thanks @lshep, that all makes sense and I have sorted all the errors and have bumped the version and pushed to my git repository. However, when I try and push upstream to bioconductor, I get the following error:

To git.bioconductor.org:packages/ewceData.git
 ! [remote rejected] main -> main (hook declined)
error: failed to push some refs to 'git@git.bioconductor.org:packages/ewceData.git'

**Comment by lshep** [comment]
Please show the full command with output.  I assume you followed the instructions to set up the remotes but please be sure there is a upstream remote that points to `git@git.bioconductor.org:packages/ewceData.git` you can check this with `git remote -v`  .  github changed the default branch naming master to main however our build system still uses master.  Two thoughts, 1. make sure to `git fetch --all`  before trying to push and 2. make sure to explicitly state the branch you would like to push to `git push upstream master`

**Comment by Al-Murphy** [comment]
I believe the upstream is set to bioconductor git, see the output of `git remote -v`:

`origin	https://github.com/neurogenomics/ewceData.git (fetch)
origin	https://github.com/neurogenomics/ewceData.git (push)
upstream	git@git.bioconductor.org:packages/ewceData.git (fetch)
upstream	git@git.bioconductor.org:packages/ewceData.git (push)`

Based on your advice, I reran `git fetch --all`:

`Fetching origin`
`Fetching upstream`

and then tried to push, I use main rather than master so I used `git push upstream main` but still got:
  
Total 0 (delta 0), reused 0 (delta 0)
remote: FATAL: W refs/heads/main packages/ewceData Al-Murphy DENIED by fallthru
remote: error: hook declined to update refs/heads/main
To git.bioconductor.org:packages/ewceData.git
 ! [remote rejected] main -> main (hook declined)
error: failed to push some refs to 'git@git.bioconductor.org:packages/ewceData.git'

**Comment by lshep** [comment]
Again -- our default branch is not main... please do `git push upstream master`

**Comment by Al-Murphy** [comment]
Sorry I missed what you meant about master/main, I thought you could still use either (as per this [documentation](https://bioconductor.org/developers/how-to/git/new-package-workflow/)). I tried using master rather than main and I'm still getting an error: 

`git push upstream master` 

`error: src refspec master does not match any`
`error: failed to push some refs to 'git@git.bioconductor.org:packages/ewceData.git'`

Should I rename my main branch as master or would that make any difference?

Also note I ran `git merge origin/main` rather than master earlier when setting up the git Bioconductor upstream, again per the document. I'm not sure if this is affecting things?

**Comment by lshep** [comment]
You should be able to leave yours as main while pushing to our master.  Could you try 
`git push upstream main:master`

**Comment by Al-Murphy** [comment]
That failed and I also tried forcing it which didn't seem to work either:


```
git push upstream main:master                           
To git.bioconductor.org:packages/ewceData.git
 ! [rejected]        main -> master (non-fast-forward)
error: failed to push some refs to 'git@git.bioconductor.org:packages/ewceData.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

git push -f upstream main:master
Total 0 (delta 0), reused 0 (delta 0)
remote: Error: Illegal version bump from '0.99.1' to '0.9.1'.
remote: 
remote: Check http://bioconductor.org/developers/how-to/version-numbering/
remote: for details.
remote: 
To git.bioconductor.org:packages/ewceData.git
 ! [remote rejected] main -> master (pre-receive hook declined)
error: failed to push some refs to 'git@git.bioconductor.org:packages/ewceData.git'
```

**Comment by lshep** [comment]
@nturaga   advice

**Comment by Al-Murphy** [comment]
@lshep, @nturaga no need to look into this anymore, I removed the upstream branch and then re-initiated it and it seems to be working find now. Thanks for the help!

**Comment by Al-Murphy** [comment]
Hey @lshep, the remaining issue is
```
Quitting from lines 91-99 (ewceData.Rmd) 
Error: processing vignette 'ewceData.Rmd' failed with diagnostics:
could not find function "cortex_mrna"
--- failed re-building 'ewceData.Rmd'
``` 

which relates to `cortex_mrna <- cortex_mrna()` in the vignette and is Windows specific. This is odd since I have already libraried the package and my load function from ExperimentHub is working correctly for the other operating systems. A re you aware of some naming errors with ExperimentHub on Windows that I could be committing here?

**Comment by lshep** [comment]
@hpages  do you know of any stipulations regarding windows for this use case?  

In the meantime I will review based on the other two platforms.  Cheers

**Comment by Al-Murphy** [comment]
I tried making some changes to the package to sort the issue but the problem with using the package on Windows seems to persist. Not sure if either you @lshep or @hpages have come across this before? Currently the package won't install on Windows with the following error:
```
Error: package or namespace load failed for 'ewceData':
 .onLoad failed in loadNamespace() for 'ewceData', details:
  call: fun(libname, pkgname)
  error: no objects found
```

**Comment by Al-Murphy** [comment]
AdditionalPackage: https://github.com/NathanSkene/EWCE

**Comment by mtmorgan** [comment]
Nathan Skene is the maintainer of EWCE, but @Al-Murphy is submitting the package; @Al-Murphy should be the maintainer.

**Comment by Al-Murphy** [comment]
Hi @mtmorgan. I have updated the maintainer as suggested and references across the two packages and have bumped their versions and pushed the changes. Will the EWCE package be assigned to someone and have a check run similar to the ewceData package? There was an issue with file size with EWCE but I have corrected this in the latest push too.

**Comment by mtmorgan** [comment]
yes, the EWCE package will be assigned to the current reviewer, and will be built on version bump, once it has been 'moderated'; the maintainer issue was blocking the moderation step, so this will occur when packages are next moderated (usually once every two or three days).

**Comment by Al-Murphy** [comment]
Hi @mtmorgan, just wondering if packages have been moderated since your last message? EWCE hasn't been assigned and I want to know in case there is something else blocking the moderation step that I can resolve.

**Comment by mtmorgan** [comment]
@vjcitn is working on this; I think the current stumbling block is resolving the previous EWCE package that we still have a repository for with your new contribution, which might not be derived from git@git.bioconductor.org:packages/EWCE ?

**Comment by Al-Murphy** [comment]
Ah okay that's no problem. I think it may not have been, EWCE originally went on Bioconductor some time ago and, at the time, I don't think the submission process was the same

**Comment by Al-Murphy** [comment]
Hi @mtmorgan, @lshep I believe that is the old deprecated version of EWCE that the check was ran against not from the repository I am submitting

**Comment by vjcitn** [comment]
Yes, there was something about NathanSkene in the repo that was used.  I will try to straighten this out.

**Comment by lshep** [comment]
I think we have corrected the issue.  I have just kicked off a manual build for the package and you should have a build report shortly.

**Comment by Al-Murphy** [comment]
That seems odd that it failed on all three OS, it is passing with no warnings or errors locally on my Mac

**Comment by lshep** [comment]
I can reproduce the linux error locally on my computer.  Please make sure that you are using R-devel (R 4.1) and have updated all Bioconductor package dependencies with `BiocManager::valid()` .

**Comment by Al-Murphy** [comment]
@lshep can you start antoher manual build on EWCE. The error was caused by something in ewceData which I have fixed and bumped the version of but since no change has been made to EWCE it won't rebuild

**Comment by lshep** [comment]
done. You should have a new report shortly.   I just happened to notice you are writing files to a users home directory by default.  That should never be done.  Please update the code to use `tempdir()` or `tempfile()`  by default in the vignettes, examples, tests.  The files that are written are 
```
CellTypeData_kiCortexOnly.rda
CellTypeData_kiCortexOnly_1to1only.rda
```

**Comment by Al-Murphy** [comment]
Hi, 

The latest build threw up some strange errors. Firstly, is there any way to extend the check time for the tests to avoid the timeout, the size of the datasets is necessary to hit all conditions in the package for the test coverage:

```
TIMEOUT: R CMD check exceeded 14 mins
```

Also there seems to be a Windows specific error 
```
ERROR: dependencies 'RNOmni', 'HGNChelper' are not available for package 'EWCE'
```

**Comment by lshep** [comment]
I'll check on the windows packages not being available.  They look like they have windows binaries so I'm surprised they are not installing.  I'll let you know when I know more about the windows build. 

No we do not extend the time limits for packages.  Keep in mind we build and check every Bioconductor package nightly so we need to have some limits in place for resources.  We do respect and encourage test coverage for package functionality.  Might I suggest looking at implementing [long tests](http://bioconductor.org/developers/how-to/long-tests/).  You would want to keep some testing of main functionality in daily testing but could do more extensive testing with the long tests that are run once a week with a more lenient time.

**Comment by Al-Murphy** [comment]
Hi @lshep, 

That makes sense with the nightly build, thanks for clarifying. Looking at the documentation page you sent, it specifies tests can run for an accumulated 40 minutes however, my tests don't run for near that long, has that limit changed? In fact when I run R CMD Check locally the tests complete in 8 minutes and the full check takes 24 minutes (see image below) which is a lot shorter than the time taken in the build report when it timed out. Is the 40 minutes for the full R CMD check? And will is this error just not be reproducible locally and is there some reason running the check locally takes far less time than in the build report?


![image](https://user-images.githubusercontent.com/62257358/111764514-2f4fcf00-889b-11eb-9a60-83e5576fe871.png)

**Comment by vjcitn** [comment]
@hpages do BBS timings arise in the context of multi-package contention for resources?  Can the user estimate BBS check times independently?

**Comment by lshep** [comment]
Sorry for the confusion.  The single package builder does not use 40 minutes as the timeout limit.  That is for the daily builders. For new package submissions the timeout limit is 15 minutes as we do not want every package submitted to utilize the max time. Those timeout limits are for the entire R CMD check to run.

**Comment by Al-Murphy** [comment]
So the 15 minutes is for the full R cmd check run? As in what's currently taking 24 minutes?

**Comment by lshep** [comment]
Correct.

**Comment by Al-Murphy** [comment]
Hi @lshep,

There still seems to be a Windows specific issue running EWCE. Did anything come to light when looking into this previously? Other than this the only issue is a warning for R CMD Check taking longer than 10 minutes, I assume this is okay given you mentioned a 15 minute limit?

Thanks!

**Comment by hpages** [comment]
@Al-Murphy Maybe one thing that would help here is that you force creation of a permanent ExperimentHub cache so the data doesn't need to be re-downloaded each time the SPB runs `R CMD build` or `R CMD check` on the package. Once all the data makes it to the local cache, any subsequent build will be more reliable and faster.

@lshep What's the proper way to do this? By specifying `ask=FALSE` in the call to `ExperimentHub()`? I don't see any mention of the `ask` argument in `ExperimentHub()`'s man page.

**Comment by lshep** [comment]
@hpages  Yes. As discussed with the Bioc team last week,  we will be altering the caching behavior so when in a non-interactive session it will start creating the permanent location automatically instead of a `tmp` which will help on our servers as well as other institutional servers.  I'm in process of fixing this behavior but was out of office last week.  I'm hoping to have it implemented in Bioc devel by the end of this week.   Yes the `ask=FALSE` would force create in the meantime, we didn't like to heavily advertise this as it forces the install location for a user even in a non-interactive session but it would force create the cache.  When I update for the caching change, I'll make sure this is all better documented.

**Comment by Al-Murphy** [comment]
Thanks @lshep. Should I wait then for the change to be made at the end of the week (if you wouldn't mind commenting here when that happens if so) or will I change `ask=FALSE` to be able to make the change immediately (and possibly readdress later)?

**Comment by lshep** [comment]
Hold off on adding the `force` for now (It will actually be a good testing case for our builders to know we have one in the queue that should create it).  I'll try to get to reviewing your packages by the end of the week or early next too so there can be other revisions if necessary. Cheers

**Comment by lshep** [comment]
Please see an initial review of EWCEdata and EWCE  packages. 


**_ewceData_**


**DESCRIPTION**

- [ ] We recommend having `LazyDatat: true` removed from DESCRIPTION. We have rarely found useful and can slow package installation.


**inst**

- [ ] Please include an `inst/script` directory that has a file describing how the object that was placed in experiment hub was created. Include source information and any preprocessing; it can be code, sudo-code, or text.


**vignette**

- [ ] We recommend having a table of contents. I think this should be an option with `toc: true`

- [ ] In vignette, man, and tests you download a file from google drive it seems? Can this file be included in the package if it is different than your files in the hub or included in the hub.  We generally do not allow personal drives for storing data as it cannot be tracked and monitored.

- [ ] What is the distinction between the data you are downloading from the txt file vs what is stored in the hubs?  What is the relation?

- [ ] You don't show any extraction of data from the hubs. 

**R**

- [ ] We like to see interoperability with Bioconductor objects and classes.  Any Rectangular feature x sample data should be in SummarizedExperiment format as this is what is traditionally used in Bioconductor. The results of  `load.linnarsson.sct.data` seem appropriate to be in SummarizedExpeirment format.  I'm not sure if this also means updating the data provided in the hubs as well? 

- [ ] Functions should not contain `.` as it indicates a S3 disbatch. Please use camelcase or underscores. 

**General**

- [ ] Any file download should not download to a working directory but to a  temporary directory with `tempdir()`




---------------------------------------------------------

**_ewce_**


**General**

- [ ] Please remove the `_pkgdown.yml`, `Dockerfile` and `docker_push` from the main branch pushed to git.bioconductor.org. While we recognize these are useful tools we are trying not to have external configurations on our system in case we implement anything of our own that could conflict. We recommend moving them to a different branch

**DESCRIPTION**

- [ ] Please remove `LazyData: true` we have rarely found it useful and can  actually slow package installation.
  
**NAMESPACE**

- [ ] Please use camelcase or underscores for naming functions. The dot `.`  indicates S3 disbatch and should be avoided.  

**README**

- [ ] Please include Bioconductor installations instructions

**NEWS**

- [ ] News file is formatted improperly.  Please see `?news` in R or [news guidelines](http://bioconductor.org/developers/package-guidelines/#news). In particular regarding heading sections that should take the format `Changes in version x.y.z` 

**inst**

- [ ] Please also include an inst/scripts directory that describes how the data in inst/extdata was created. It can be code, sudo-code, or text but should include any source/version information and any preprocessing of files before including in the directory for release to users.

- [ ] Are these really `extdata` objects? Perhaps they better belong in a doc or some other inst directory as extdata generally implies data objects to be loaded or referenced. 

**vignettes**

- [ ] We recommend having a table of contents. I think this should be an option with `toc: true`

- [ ] Show Bioconductor installation instructions. 

- [ ] Again In vignette, you download a file from google drive it seems? If you need this file for examples it should also be part of the ecweData sets that are available via download from the hub. We do not allow personal drives for storing data as it cannot be tracked and monitored. It seems like this file should also be included in the hubs. 

- [ ] Any recommended downloaded file should be cached. The MRK_List2 for instance should probably have a designated download function where you do the caching in the backend if the files are not able to be included in the experimenthub data you already provide. It is possible to reference data from other hosted sites through experimenthub while not copying to S3 as long as the licensing allows such. 

- [ ] Files should be defaultly written to a `tempdir()` or using `tempfile()` currently while running your vignette there are files populating my home directory `CellTypeData_` and a directory `BootstrapPlots`. 

- [ ]your functions should  also take SummarizedExperiment objects the classic object for representing rectangular feature x sample data in Bioconductor. Given that your package is designed to work with single cell transcriptome data you might also look at the SingleCellExperiment class. It should be easy enough to check for the class in the function and extra the matrices if necessary for use with these objects. 

- [ ] We like to see interoperabiity with other standard Bioconductor objects as much as possible. There could be other areas that
  could show overlap like how to get gene lists and such with other Bioconductor packages. There are some Gene set classes that should be able to make wrappers to your functions to use. like BiocSet::BiocSet and GESABase::GeneSet


**R/man**

- [ ] use message instead of print.



Please address the above issues in both packages and trigger rebuilds with version bumps.  When you are ready for a re-review please comment here addressing and commenting on the above issues.  

Cheers,

**Comment by Al-Murphy** [comment]
Hi @lshep, 

Thank you for the review notes. I have updated and submitted changes to ewceData. See below for how I resolved the issues you noted. I will deal with EWCE as a separate comment. Also not there was a fail on Windows, this is the same issue discussed with @hpages which I hope will be resolved with your work on altering the caching behaviour.

ewceData

DESCRIPTION

- [x] We recommend having LazyDatat: true removed from DESCRIPTION. We have rarely found useful and can slow package installation. - I removed this.

inst
- [x] Please include an inst/script directory that has a file describing how the object that was placed in experiment hub was created. Include source information and any preprocessing; it can be code, sudo-code, or text. - I have updated to include this.

vignette

- [x]  We recommend having a table of contents. I think this should be an option with toc: true - Added

- [x] In vignette, man, and tests you download a file from google drive it seems? Can this file be included in the package if it is different than your files in the hub or included in the hub. We generally do not allow personal drives for storing data as it cannot be tracked and monitored. - I have removed these downloads along with the load.linnarsson.sct.data. The purpose of the function was to show how the data was formatted but I think it caused more confusion than what it was worth keeping it.

- [x] What is the distinction between the data you are downloading from the txt file vs what is stored in the hubs? What is the relation? - They were the same, it was to show how to derive the data. This has been removed now.

- [x] You don't show any extraction of data from the hubs. - Added to vignette

R

- [x] We like to see interoperability with Bioconductor objects and classes. Any Rectangular feature x sample data should be in SummarizedExperiment format as this is what is traditionally used in Bioconductor. The results of load.linnarsson.sct.data seem appropriate to be in SummarizedExpeirment format. I'm not sure if this also means updating the data provided in the hubs as well? - Function has been removed so this shouldn't be necessary

- [x] Functions should not contain . as it indicates a S3 disbatch. Please use camelcase or underscores. - Function removed so not necessary but I will bare it in mind for EWCE and any other packages I develop.

General

- [x] Any file download should not download to a working directory but to a temporary directory with tempdir() - Removed so not necessary but again I'll keep it in mind

**Comment by Al-Murphy** [comment]
@lshep, I'm nearly through the changes for EWCE but one question I had about your point below: 

```
Please remove the _pkgdown.yml, Dockerfile and docker_push from the main branch pushed to git.bioconductor.org. While we recognize these are useful tools we are trying not to have external configurations on our system in case we implement anything of our own that could conflict. We recommend moving them to a different branch
```

It was suggested in the Bioc-devel mailing list to just add _pkgdown.yml to the .Rbuildignore file. Would this be suitable? It would obviously be a very easy solution and would allow me to keep the pkgdown functionality which I really like for producing my vignette on a website easily.

Secondly, would this also be suitable for the two docker files? These are less important in my mind but again this would be beneficial

Thanks!

**Comment by Al-Murphy** [comment]
Hi @lshep, I have now made all the changes to EWCE and have pushed the new version. See below for my notes:

ewce

General

- [x] Please remove the _pkgdown.yml, Dockerfile and docker_push from the main branch pushed to git.bioconductor.org. While we recognize these are useful tools we are trying not to have external configurations on our system in case we implement anything of our own that could conflict. We recommend moving them to a different branch - _Done, I'm using a separate staging branch for these instead_

DESCRIPTION

- [x] Please remove LazyData: true we have rarely found it useful and can actually slow package installation. - _Removed_

NAMESPACE

- [x] Please use camelcase or underscores for naming functions. The dot . indicates S3 disbatch and should be avoided. - _Updated, I went with underscore approach for cohesion with other functions._
README

- [x] Please include Bioconductor installations instructions - _Done in README and vignette_

NEWS

- [x] News file is formatted improperly. Please see ?news in R or news guidelines. In particular regarding heading sections that should take the format Changes in version x.y.z - _Done, I have updated the format as described_

inst

- [x] Please also include an inst/scripts directory that describes how the data in inst/extdata was created. It can be code, sudo-code, or text but should include any source/version information and any preprocessing of files before including in the directory for release to users. - _Added_

- [x] Are these really extdata objects? Perhaps they better belong in a doc or some other inst directory as extdata generally implies data objects to be loaded or referenced.- _Created a new inst directory to hold these, they are not data objects_

vignettes

- [x] We recommend having a table of contents. I think this should be an option with toc: true - _Added_

- [x] Show Bioconductor installation instructions. - _Done_

- [x] Again In vignette, you download a file from google drive it seems? If you need this file for examples it should also be part of the ecweData sets that are available via download from the hub. We do not allow personal drives for storing data as it cannot be tracked and monitored. It seems like this file should also be included in the hubs. - _I have removed this, I do this a few times as a means of showing how data available from ewceData was derived but I agree this is confusing so I have removed it. I have also added another data source to ewceData to make things more clear._

- [x] Any recommended downloaded file should be cached. The MRK_List2 for instance should probably have a designated download function where you do the caching in the backend if the files are not able to be included in the experimenthub data you already provide. It is possible to reference data from other hosted sites through experimenthub while not copying to S3 as long as the licensing allows such. - _This download has been removed so not necessary to cache_

- [x] Files should be defaultly written to a tempdir() or using tempfile() currently while running your vignette there are files populating my home directory CellTypeData_ and a directory BootstrapPlots. - _I have updated these to a temp directory_

- [x] your functions should also take SummarizedExperiment objects the classic object for representing rectangular feature x sample data in Bioconductor. Given that your package is designed to work with single cell transcriptome data you might also look at the SingleCellExperiment class. It should be easy enough to check for the class in the function and extra the matrices if necessary for use with these objects. - _I have updated the relevant functions to accept GRange SummarisedExperiment and SingleCellExperiment objects. Using these is also now discussed in the vignette._

- [x] We like to see interoperabiity with other standard Bioconductor objects as much as possible. There could be other areas that could show overlap like how to get gene lists and such with other Bioconductor packages. There are some Gene set classes that should be able to make wrappers to your functions to use. like BiocSet::BiocSet and GESABase::GeneSet - _I have added to the vignette describing how these objects can be used in EWCE_

R/man

- [x] use message instead of print. - _Done_


Separately, is there any update on the Cache approach for ExperimentHub? I noted that my latest ewceData and EWCE build had more errors than usual which seem related?

Thanks,
Alan.

**Comment by Al-Murphy** [comment]
Hi @lshep, @hpages, has there been any update on the changes to the ExperimentHub package in regards to caching? Am I right to still assume this is what's causing the errors on my builds? Is there anything I can be doing to improve the package in light of the upcoming submission deadline?

Thanks,
Alan.

**Comment by lshep** [comment]
@Al-Murphy  I've been doing some follow up tests but yes it does appear the caching is now active for the SPB.  If you would like to try and kick off a new build of the package by bumping the version. It might take too builds, one to do the caching,  and one to run the code using the cached file instead of downloading.

**Comment by Al-Murphy** [comment]
Hi @lshep, I seem to still be getting errors which seem to be related to the caching (if you could check the latest build report). This is only on the data package and I haven't tried the main package - I'll run it again once this is resolved.

**Comment by lshep** [comment]
In the latest build report I do not see ERROR's related to caching.  I see an ERROR related to registration on the support site.

**Comment by Al-Murphy** [comment]
Hi @lshep , thanks for your help already today but it seems I still have time out issues with the package for windows and a warning for Linux. Is there any advice on what I should do next to get around this? I imagine I must be close with the time seeing as it passed on Mac? @hpages just commenting you in on this as I know we discussed timeouts previously.

Thanks,
Alan.

**Comment by lshep** [comment]
It may be close but it is still a very long time for a package to build and check.  Is there a way to use a smaller subset of data for the vignettes and examples?

**Comment by Al-Murphy** [comment]
I've subsetted the examples as much as possible and unfortunately the vignette can't really be sped up since it replicates the associated paper's results. I know the most time consuming parts are the tests and examples.

**Comment by lshep** [comment]
I'll continue with the review.  I should have a re-review in the next few days

**Comment by Al-Murphy** [comment]
Hi @lshep, is it acceptable to use a `donttest` wrapper for two examples in my exported functions? I will still have greater than 80% with running examples but this will greatly improve my runtime.

**Comment by lshep** [comment]
Are there other tests or anything for the functions that would be in the donttest?   I think that would be reasonable as long as the majority are run.

**Comment by Al-Murphy** [comment]
Yep unit tests still cover 80+% of the code so they would be covered. I think with `dontest` checks that it's valid R code anyway. Thanks!

**Comment by lshep** [comment]
Yes that is acceptable then

**Comment by Al-Murphy** [comment]
Hi @lshep , is the warning for a run time over 20 minutes on Windows acceptable? Note that the run time is below 10 for Linux and I assume the same on Mac.

**Comment by lshep** [comment]
Yes this is acceptable.  I try and review your packages over the next few days.

**Comment by Al-Murphy** [comment]
Thank you! I won't be making any changes in the meantime then

**Comment by lshep** [comment]
I can hold off if you would like to still make changes?

**Comment by Al-Murphy** [comment]
No no I have no more changes I want to make, sorry I was just confirming for you so you know things won't change while you are in the middle of a review!

**Comment by lshep** [comment]
Thank you for taking the time to apply the changes.  The packages are in an acceptable state for inclusion into Bioconductor.

**Comment by Al-Murphy** [comment]
Thank you @lshep for all your help and work on this, I realise it wasn't the easiest of packages!

Thanks,
Alan.

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Al-Murphy.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ewceData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ewceData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by vjcitn** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Al-Murphy.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("EWCE")`. The package 'landing page' will be created at

https://bioconductor.org/packages/EWCE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
