### ISSUE TITLE
ClusterJudge

### ISSUE THREAD

**Issue by pasculescu** [Bioconductor/Contributions#390]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pasculescu/ClusterJudge

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
There is no vignette and no re-use (for interoperability and robust reproducible research) of Bioconductor packages and data representations. Despite thematic relevance, it is not suited for Bioconductor.

**Comment by pasculescu** [comment]
I have added an intro vignette and updated the code, added examples.
I would like to know if this improved version might be considered for inclusion in bioconductor.
Thanks,
Adrian

**Comment by pasculescu** [comment]
I have registered myself at bioc-devel and I fixed an error related to testthat in order to fix the errors.

Should I remove/ or further simplify some of the examples! in order to get rid of the TIMEOUT?
On my mac the whole CHECK  ( R CMD check ClusterJudge_0.99.0.tar.gz) takes about 6 min.

Do I have to increase the version in DESCRIPTION from 0.99.0 to 0.99.1 for example ? Or should I first try to reduce the examples first and then increase the version in DESCRIPTION?
Thanks,
Adrian Pasculescu

**Comment by lshep** [comment]
Yes please simplify or use smaller test cases to reduce the time.  Make sure the webhook is set up and then increase the version number from 0.99.0 to 0.99.1 to kick off a new build of the package.   I would try to reduce the examples first since currently the timeout will still occur.

**Comment by pasculescu** [comment]
Do I have to do anything else to see in the end ClusterJudge in the bioconductor list of available packages?
Thanks,
Adrian

**Comment by lshep** [comment]
Thank you for your submission.  Here are some initial comments: 

Overall concern:
It would be nice if there was some connection to other Bioconductor clusteringfunctions or an example of how this is used with Bioconductor packages/functions.  Some packages marked for clustering that are already in Bioconductor can be found [here](http://bioconductor.org/packages/release/BiocViews.html#___Clustering)



DESCRIPTION:  
- [ ] fix note: Malformed Description field: should contain one or more complete sentences.


NAMESPACE: 
- [ ] Do you really want to export all functions? `exportPattern("^[[:alpha:]]+")` It appears that some of your functions may be internal and don't need to be exported. only export functions that the user will utilize. 


NEWS:
- [ ] file should be in top level directory not in inst



VIGNETTE: 
- [ ] spell and punctuation check. 
- [ ] so what conclusion do you draw from the example data... it went down but then goes up? Is this hyperbola of results expected? 


CODE:
- [ ] don't use `"."` in function names.  It implies class structure and dispatch. Use either camel case or underscores. 
- [ ] you display plots when performing the analysis. are there options to save these. ie: consolidate.entity.attribute has a plot pop up and disappear.  If these are showing cutoffs or other useful information, an option to save might be useful. 
- [ ] can download.yeast.go.mappings be generalized and not specific to the yeast genome? same for download.Yeast.go.terms.  - it seems these are helper functions only related to the yeast genome because that is what your example data is?  
- [ ] Write seq_len(n) or seq_along(x) rather than 1:n or 1:length(x). This protects against the case when n or length(x) is 0 (which often occurs as an unexpected ‘edge case’ in real code) or negative.


Please address these concerns and comment back here with how the code has been changed or with further explanation.  Thank you

**Comment by pasculescu** [comment]
Thanks for comments and suggestions. I am working on resolving/implementing them.
Adrian

**Comment by pasculescu** [comment]
Hello again,
I hope I have addressed all your concerns:
* Added connection to other clustering Bioconductor packages (at the end of vignette for example)
* fixed DESCRIPTION for full phrase
* exporting only the needed functions in NAMESPACE
* moved NEWS to top level
* Vignette: spell check done, improved and clarified conclusion
* renamed functions so they do not include . in names
* added function arguments to save plots and provided examples to re-plot
* provided examples based on other R and Bioconductor packages to download entity-attribute data for other organisms (rat for example) in download_Yeast_GO_mapping.Rd
* replaced 1:n and similar with alternative code based on seq(...) or seq_len().

Should I bump now the  version in DESCRIPTION from 0.99.2 to 0.99.3 ?

Thanks,
Adrian

**Comment by lshep** [comment]
Yes please bump the version to 0.99.3 so that a new build and check report gets generated.  Once that is complete I will re-evaluate your package. Thank you.
