### ISSUE TITLE
MetaNeighbor

### ISSUE THREAD

**Issue by mm-shah** [Bioconductor/Contributions#542]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mm-shah/MetaNeighbor

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Your package must accept SummarizedExperiment as input; it seems ideally suited to that data structure.

**Comment by mm-shah** [comment]
@mtmorgan 

Hi Morgan, 

Thanks for your comments.

While we would ideally make our package compatible with accepted data structures, in general they are not sufficiently consistent to allow us to extract the required information for our computations. In particular, we require users to provide class labels from multiple experiments and these are often are stored in an ad hoc way under the colData within a SummarizedExperiment object 

Converting the data to a SummarizedExperiment object and then presenting it as an input will then become an extra task on user's side as they would have to collect all the data required (which will come from multiple studies/sources and part of which would be study specific), convert it back to a SummarizedExperiment object with specific requirements for the colData formatting, and then submit it to be used in the package. 

So due to these reasons, I consider that in the current situation it is beneficial to provide the gene x sample matrix and sample information matrix to the package directly. We are happy to include information in the vignette about how to curate these matrices from SummarizedExperiment objects if that would be helpful.

**Comment by mtmorgan** [comment]
Your premise is that the user does not have a SummarizedExperiment to begin with, but the point of interoperability is that this is the starting point. Also, it is better for the user to construct the SummarizedExperiment and align appropriate sample annotations, than to rely on multiple objects each being aligned correctly.

Revise your functions to accept SummarizedExperiment. Presumably you will either require or allow the user to specify the colData column names that are to be used, and your first step will be to validate that these columns are present and of the appropriate type.

**Comment by mm-shah** [comment]
Hi @mtmorgan , I have updated the functions to accept SummarizedExperimnet object as input. Please have a look at the package. Thank you.

Best regards,
Manthan

**Comment by mm-shah** [comment]
Hi @mtmorgan, @LiNk-NY ,

I hope you had a great holiday. I was wondering if I can get some feedback on the package. I updated R scripts to accommodate SummarizedExperiment input as mentioned by @mtmorgan . I humbly request you to review my package and revert with you thoughts and concerns.

Thank you.

Best regards,
manthan

**Comment by LiNk-NY** [comment]
Hi Manthan, @mm-shah 
I will be looking at your package soon. 
Thank you for your patience. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Manthan, @mm-shah 

Thank you for your submission. Please find the review below.

Best regards,
Marcel

---

# MetaNeighbor #542

## DESCRIPTION

* You can just provide the `Author@R` field and remove the `Author`
field.

## NAMESPACE

* It looks like some functions need to be renamed. 

## R

* `eval_obj` should be an unexported helper function. I don't see a reason for
using the function outside your package. It should return a logical TRUE/FALSE.
* Some of these checks are moot since they're already done when the
`SummarizedExperiment` is created.
* You should allow for an interface where the user can specify the name of
their `study_id`, `cell_type` variables. This will allow more flexibility in
variable names.
* Using the `metadata` slot for required data leads me to believe that you
should be looking for a structure that extends `SummarizedExperiment`. Perhaps
one already exists with a `genesets` or similar slot.
* Your main function could just be the name of the package `MetaNeighbor`.
It should not save a file at all. The user can do that if he/she chooses to.
* You can provide your `mn_data` as a `SummarizedExperiment` rather than a
simple matrix.
* Allow the user to select the assay in the `SummarizedExperiment` with
by including an `i` argument in your function with a default to `1L`.
So that your data is obtained by `SummarizedExperiment::assay(mn_data, i = i)`
* Avoid growring a vector. Use the allocate and fill method
(line 55 in `get_top_hits.R`)

Syntax: 
* Avoid the use of `1:length(x)` sequence generation. Use the more robust
`seq_along` or `seq_len`. 
* `length(which(is.na(x) == FALSE))` could be simplified to `sum(!is.na(x))`
* Use name values where possible when subsetting
(e.g., `vector <- dataframe[["variable"]]` instead of `dataframe[[1]]`)
* Please use camelCase function naming conventions and remove prefixes such
as `run_`. Keep function names short where possible
(e.g., `neighbor_voting_LeaveOneExpOut` -> `voteNeighbor` and document
the leave-one-out method)
* Avoid overwriting a function symbol such as `c` with an object created
in your function. Use a different name. 

## vignettes

* We will not accept static vignettes. Please make your code runnable in
the package vignette

**Comment by mm-shah** [comment]
Hi Marcel, 

Thank you for the feedback. I'll revert with my response shortly.

Best regards,
Manthan

**Comment by mm-shah** [comment]
Hi Marcel,

I'll make all the mentioned changes. I have a few concerns regarding whom I would appreciate your feedback. They are as follows:

**R**
•    “eval_obj should be an unexported helper function. I don't see a reason for using the function outside your package. It should return a logical TRUE/FALSE.”
I’ll remove the export tag from the eval_obj’s Roxygen file. That’ll remove the eval_obj from the NAMESPACE file and it won’t be exported then. 

•    “Some of these checks are moot since they're already done when the SummarizedExperiment is created.”
Instead of keeping eval_obj script I'll keep dedicated checks in the functions. 

•    “You should allow for an interface where the user can specify the name of their study_id, cell_type variables. This will allow more flexibility in variable names.”
I'll rewrite function arguments to allow users to point to locations in their Summarized Experiment Objects for the required data. 
ex.: run_MetaNeighbor(data = SummarizedExperiment::assays(mn_data)[[geneMatrix]],
                                      experiment_labels =mn_data$study_id,
                                      celltype_labels = mn_data@colData@metadata$cell_labels,
                                      genesets = mn_data@metadata$genesets)

•    “Using the metadata slot for required data leads me to believe that you should be looking for a structure that extends SummarizedExperiment. Perhaps one already exists with a genesets or similar slot.”
As you mentioned that all the data should be provided in the form of an SE object, I had to stuff the genesets in metadata section of SE object as I was unable to find a structure (SingleCellExperiment object, SummarizedExperiment Object, and ExpressionSet object) with a dedicated slot to store genesets. I would really appreciate if you can point out which package provides such functionality. The required genesets can either be provided in a way like which is used in the MetaNeighbor package (stuffing  a list of lists in metadata section of SE object) or as a standalone list of lists to the function as an argument. It would be better to provide the genesets as an individual argument to the function as genesets are only required in **run_MetaNeighbor** function. 

•    “You can provide your mn_data as a SummarizedExperiment rather than a simple matrix.”
mn_data is provided as a SummarizedExperiment object. The matrix is stored as an assay inside the object. Please correct me if I'm wrong.

**Comment by mm-shah** [comment]
Hi Marcel, @LiNk-NY 

Thank you for your comments. I have updated the package with all mentioned changes and it has passed R and BioC checks without errors and warnings. I humbly request you to review my submission at your earliest disposal and revert with your concerns.

Best regards,
Manthan

MetaNeighbor #542

**DESCRIPTION**
--

- [x] You can just provide the Author@R field and remove the Author field.

**NAMESPACE**
--
- [x] It looks like some functions need to be renamed.

**R**
--

- [x] eval_obj should be an unexported helper function. I don't see a reason for using the function outside your package. It should return a logical TRUE/FALSE.

  - Removed eval_obj and added function specific checks

- [x] Some of these checks are moot since they're already done when the SummarizedExperiment is created.

  - Removed the checks

- [x] You should allow for an interface where the user can specify the name of their study_id, cell_type variables. This will allow more flexibility in variable names.

- [x] Using the metadata slot for required data leads me to believe that you should be looking for a structure that extends SummarizedExperiment. Perhaps one already exists with a genesets or similar slot.

  - updated function `MetaNeighbor` (previously `run_MetaNeighbor`) to use gene sets as a separate argument (list of character vectors)

- [x] Your main function could just be the name of the package MetaNeighbor. It should not save a file at all. The user can do that if he/she chooses to. You can provide your mn_data as a SummarizedExperiment rather than a simple matrix.

  - gene-by-sample matrix is provided as an assay of SummarizedExperiment object `mn_data`

- [x] Allow the user to select the assay in the SummarizedExperiment with by including an i argument in your function with a default to 1L. So that your data is obtained by SummarizedExperiment::assay(mn_data, i = i)

- [x] Avoid growing a vector. Use the allocate and fill method (line 55 in get_top_hits.R)

**Syntax:**
--

- [x] Avoid the use of 1:length(x) sequence generation. Use the more robust seq_along or seq_len.

- [x] length(which(is.na(x) == FALSE)) could be simplified to sum(!is.na(x))

- [x] Use name values where possible when subsetting (e.g., vector <- dataframe[["variable"]] instead of dataframe[[1]])

- [x] Please use camelCase function naming conventions and remove prefixes such as run_. Keep function names short where possible (e.g., neighbor_voting_LeaveOneExpOut -> voteNeighbor and document the leave-one-out method)

- [x] Avoid overwriting a function symbol such as c with an object created in your function. Use a different name.

**vignettes**
--

- [x] We will not accept static vignettes. Please make your code runnable in the package vignette

**Comment by LiNk-NY** [comment]
Hi Manthan, @mm-shah 
Thank you for making those changes.
A few points:

* Can you include the full source of the `gene_set` data under the `@source` tag? Please use a more
descriptive dataset name.
* Try not to use names that collide with R functions such as `data` as well
* Some `1:length(x)` still exists, try using `seq_along(quant_med)`

Minor: 
* You can combine data documentation chunks into a single `data.R` file.

It is looking better! 

Best, 
Marcel

**Comment by mm-shah** [comment]
Hi Marcel, @LiNk-NY 

Thank you for comments. All the mentioned changes have been performed and please find below the response to the changes:

- [x] Can you include the full source of the gene_set data under the @source tag? Please use a more
descriptive dataset name.

  - renamed the gene_set to GOmouse and also added link to the paper in the @source tag of the documentation part

- [x] Try not to use names that collide with R functions such as data as well 

  - renamed all data references to dat

- [x] Some 1:length(x) still exists, try using seq_along(quant_med)

  - replaced all the remaining occurrences of 1:length() with seq_along(). Extremely sorry for reporting half edited package.

Minor:

- [x] You can combine data documentation chunks into a single data.R file.

  - If its not a problem, I would like to have two individual documentation files 

Best regards,
Manthan

**Comment by LiNk-NY** [comment]
Hi Manthan, @mm-shah 

Thank you for making those changes.
It looks like you're still growing a vector in `tophits.R#71`. 
Also, please use the `SummarizedExperiment` accessor functions in the vignette: 
`metadata(colData(mn_data))[["cell_labels"]]`. 
Once these changes are made, it will be ready for acceptance. 
Thank you. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Manthan, @mm-shah 

Thanks for making those changes. 
Your package has been accepted. 

Thank you for contributing to Bioconductor!

Regards,
Marcel

**Comment by mm-shah** [comment]
Hi Marcel, @LiNk-NY 

Thank you very much for your feedback on improving the package. Glad to contribute. 

Best regards,
Manthan

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mm-shah.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"MetaNeighbor\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MetaNeighbor

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by mtmorgan** [comment]
Please update your DESCRIPTION file (in your newly created Bioconductor git repository, as well as your GitHub repository) to use the correct Authors@R notation
```
MetaNeighbor master$ git diff
diff --git a/DESCRIPTION b/DESCRIPTION
index 1680c09..ad70a9e 100644
--- a/DESCRIPTION
+++ b/DESCRIPTION
@@ -2,7 +2,7 @@ Package: MetaNeighbor
 Type: Package
 Title: Method to rapidly assess cell type identity using gene sets
 Version: 0.99.12
-Author: c(person("Megan", "Crow", email = "mcrow@cshl.edu",role = c("aut", "cre")),
+Authors@R: c(person("Megan", "Crow", email = "mcrow@cshl.edu",role = c("aut", "cre")),^M
     person("Sara", "Ballouz", email = "sballouz@cshl.edu",role = c("ctb")),
     person("Manthan", "Shah", email = "shah@cshl.edu",role = c("ctb")),
     person("Jesse", "Gillis", email = "JGillis@cshl.edu",role = c("aut")))
```

**Comment by mm-shah** [comment]
Hello Martin,

The DESCRIPTION file has been updated with correct Author@R tag.

Best regards,
Manthan
