### ISSUE TITLE
samexplorer RNA-seq depth analysis

### ISSUE THREAD

**Issue by shaileshtripathi** [Bioconductor/Contributions#62]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/shaileshtripathi/samExploreR
  Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by mtmorgan** [comment]
Hi -- It looks like it contains extensive code from (R)subread. Instead of including this code, please re-factor your package so that it Imports: Rsubread and uses functionality available through Rsubread's public API.

**Comment by shaileshtripathi** [comment]
My package is building fine on Mac and Linux servers. I found one problem on windows server that it is not able to find "Rnterface.h" header file, it is giving following error, Rinterface.h: No such file or directory.
How can I solve this problem.

Also one more check error which is "REQUIRED: Maintainer should subscribe to the bioc-devel mailing" I have already subscribed to the mailing list but not approved yet.

**Comment by shaileshtripathi** [comment]
Hi @mtmorgan
 My package is building fine on Mac and Linux servers. I found one problem on windows server that it is not able to find "Rnterface.h" header file, it is giving following error, Rinterface.h: No such file or directory.
How can I solve this problem.

Also one more check error which is "REQUIRED: Maintainer should subscribe to the bioc-devel mailing" I have already subscribed to the mailing list but not approved yet.

**Comment by mtmorgan** [comment]
@shaileshtripathi from Rinterfaces.h

```
/* This header file is to provide hooks for alternative front-ends,
   e.g. GUIs such as GNOME and Cocoa.  It is only used on Unix-alikes.
```

so the header is not present on Windows. Also, please note my comment from 15 days ago about the appropriate way to use Rsubread -- via the existing package R API, rather than by including its source code again.

**Comment by shaileshtripathi** [comment]
@mtmorgan 
Hi Martin

I am aware that I should have imported the Rsubread API, but when I want to use that API I realized that they don't provide enough flexibility so that we could import functions and to analyze RNA-seq data, so we made necessary modifications inside existing functions in Rsubread and keep them for the package. We would develop our own set of API  for this analysis and update that in couple of months. But for a while we want to keep the current code in the package.

**Comment by mtmorgan** [comment]
@shaileshtripathi Have you contacted the Rsubread authors with a (pull?) request to expose the API you are interested in?

**Comment by shaileshtripathi** [comment]
@mtmorgan 
No, I did not , we used their code available from bioconductor because our approach is related to the "sequence depth analysis" which is related with the random sample of sequence depth and did not find any function in Rsubread which allows to do so, therefore we made some modification inside the code.

**Comment by mtmorgan** [comment]
@shaileshtripathi you'll have to help me see what you've done by cleaning up the code to include essential functionality and a clear 'diff' between the source files in Rsubread and your own source files. I'm very reluctant for you to simply copy Rsubread's source code, because this means that bug fixes and improvements in Rsubread are not propagated to your package. Rather than 'Have you contacted...' I should have said 'Contact the Rsubread authors with a pull request to expose the API you are interested in'.

**Comment by shaileshtripathi** [comment]
@mtmorgan Ok, thanks ya sure I will contact them regarding to use API according to my need.

**Comment by mtmorgan** [comment]
It looks like your package is almost ready for review. Can you clean up the missing imports and other notes and warnings from the build report, and subscribe to the Bioconductor 'devel' mailing list to remove the remaining ERROR flag? I will then review this package.

Alternatively, if you'd like to continue to develop your  package before review, please remove the web hook and close this issue, develop it on your own system, and when ready open a new issue?

**Comment by mtmorgan** [comment]
It looks like your package still includes Rsubread code rather than using functionality exposed by the Rsubread package or other Bioconductor tools. Also, it looks like there are additional easily corrected errors or warnings. I suggest either that the package be updated to avoid using Rsubread code directly and that the R code be updated to address the minor remaining issues, or that we close the issue and you can resubmit when you've had a chance to revise your package in line with these requirements.

From what I understand, you have been in touch with the Rsubread author and they have given you guidance on how to avoid using Rsubread C code directly. Please let me know promptly how you would like to proceed.

**Comment by shaileshtripathi** [comment]
Hi Martin,

We have removed the dependencies of samExploreR on Rsubread I updated it
long ago but it is not accepted yet, can you please take a look on that.

Best,
Shailesh

**Comment by mtmorgan** [comment]
I asked for clarification on the status of your package on August 23, and when you did not respond declined the package on September 7. I take it you would now like your package to be considered for review. I will re-open the issue, and will proceed with a review when the remaining warnings and errors are addressed; see the most recent build report.

**Comment by shaileshtripathi** [comment]
Hi Martin,

I have made required changes in the "SamExploreR" package in order to
compile it on bioconductor's server perfectly. Although it is not able to
compile on windows server because of its dependency on Rsubread. I would
like to suppress its compilation for winodws as it is done for Rsubread
package. Other than that it seems fine to me for review.

Looking forward to your reply.

Best,
Shailesh

**Comment by shaileshtripathi** [comment]
Hi Martin,

I have made required changes in the "SamExploreR" package in order to
compile it on bioconductor's server perfectly. Although it is not able to
compile on windows server because of its dependency on Rsubread. I would
like to suppress its compilation for winodws as it is done for Rsubread
package. Other than that it seems fine to me for review.

Looking forward to your reply.

Best,
Shailesh

**Comment by mtmorgan** [comment]
Please address the WARNING messages on non-Windows platforms.

**Comment by shaileshtripathi** [comment]
Hi Martin,

The samExploreR seems working fine on bioconductor for submission. Only
thing is that it is not able to compile for windows because of its
dependency on Rsubread, how can it be suppressed for windows.

Looking forward for the review of samExploreR soon.

Best,
Shailesh

**Comment by mtmorgan** [comment]
One easily fixed problems remains before the review will start

```
* checking R code for possible problems ... NOTE
.gg_color_hue: no visible global function definition for hcl
exploreRep: no visible global function definition for aov
exploreRob: no visible global function definition for aov
plotsamExplorer: no visible binding for global variable f
plotsamExplorer: no visible binding for global variable value
plotsamExplorer: no visible binding for global variable group
plotsamExplorer: no visible global function definition for runif
Undefined global functions or variables:
  aov f group hcl runif value
Consider adding
  importFrom("grDevices", "hcl")
  importFrom("stats", "aov", "runif")
to your NAMESPACE file.
```

**Comment by shaileshtripathi** [comment]
Hi Martin,

I corrected the errors but a strange versioning error is coming now and
since I changed the version number it is no longer compiling. Now the
current version is 0.99.50.

Best,
Shailesh

**Comment by mtmorgan** [comment]
Submitted packages are supposed to have version 0.99.x, where x starts at 0 and is incremented by 1 for each submission that requires re-building, 0, 1, 2, ..., 9, 10, 11, ... At some point you decided to use version 1.0.0, but that was an error. It seems that the single package builder is not building at the moment, this is likely a problem on our end and we will manually start the build process.

**Comment by mtmorgan** [comment]
please ignore the warning about version number 'should be even in release'...

**Comment by shaileshtripathi** [comment]
Hi Martin,

Is the package fine for review or should I need to change anything.

Best,
Shailesh

**Comment by shaileshtripathi** [comment]
Hi Martin,

Is the package fine for review or should I need to change anything.

Best,
Shailesh

**Comment by mtmorgan** [comment]
Yes I will review the package in its current state.

**Comment by shaileshtripathi** [comment]
Hi Martin,

Is package still under review I did not receive any information so far.

Best,
Shailesh

**Comment by mtmorgan** [comment]
yes your package is still under review.

**Comment by shaileshtripathi** [comment]
Thanks for quick reply.

Best,
Shailesh

**Comment by mtmorgan** [comment]
Sorry for the delay

DESCRIPTION, NAMESPACE

- good

NEWS

- either populate with content that can be parsed by news() (see,
  e.g., GenomicRanges/NEWS) or remove
  
vignettes

- the standard latex packages enumitem.sty, sectsty.sty, and
  verbatim.sty are not needed
- carefully consider the need for additional latex sty files included
  in the preable
- \section{Dependencies} These are not necessary; the user will simply be able to

        source("https://bioconductor.org/biocLite.R")
        biocLite("samExploreR")


- \section{For developers only}: use `biocLite()` rather than
  `install.packages()`; use a vector of files. `Matrix` is a
  'recommended' package and likely installed on most user
  computers. So
  
        biocLite(c("BiocCheck", "BiocGenerics", "RUnit"))

- Instead of \begin{verbatim}, use Sweave with `eval=FALSE`; this will
  at least ensure that the code is syntactically correct. Use
  `file.path()` instead of `paste()` (or `paste0()` when `sep="")`, or
  in this case specify the path to the file using arguments to
  `system.file()`.
  
        <<load-library, eval=FALSE>>=
        library(samExploreR)
    
        ## perform subsampling
        inpf <- system.file("testdata", "Test.sam", package="samExploreR")
    
        x <- samExplore(files=inpf, subsample_d = 0.85, N_boot=5)
        @ 
        
- Use the markup `\Rcode{}` rather than LaTeX math $samExplore$ for R
  functions.
- Use `\Rcode{}` for function arguments 
- Include an evaluated code chunk that exercises the `samExplore()`
  function.
- Suggestion: Remove unnecessary whitespace (e.g., multiple blank
  lines) and wrap text to 80 columns
- Presenting LaTeX tabular data is unlikely to be useful to the user;
  better to, e.g., `head(df_sole)` (if that's the appropriate data
  structure).
- The call to `plotsamExplorer()` generates a note that seems like it
  should be avoidable, an

        > plotsamExplorer(df_intersect,font.size=3, anova=FALSE)
        Scale for 'fill' is already present. Adding another scale for 'fill', which will
        replace the existing scale.
- Bibliography.bib: include only reference actually cited.

R

- `samExplore()`: it looks like most of the arguments are passed
  directly to `featureCounts()`. A better strategy is to write the function as
  
        samExplore(..., subsample_d=1, N_boot=1, countboot=NULL) {
            .printParam(subsample_d, N_boot)
            fc <- featureCounts(...)
            ## etc
            
  This simplifies maintenance and increases readability. The man page
  documents `...` and refers the user to `featureCounts()`, ensuring
  updated and current documentation.
- The 'copy-and-append' pattern

        resultlist =  list()
        ts = c()
        for (i in 1:ncol(fc$counts)) {
            ...
            resultlist[[i]] <- restmp[[1]]
            ts = c(ts, restmp[[2]])
        }
    
  is very inefficient. Use 'pre-allocate and fill' to avoid qaudratic
  scaling and avoid using `1:ncol()` (which has surprising results
  when `ncol() == 0`)
  
        resultlist = vector("list", ncol(fc$counts))
        ts = integer(ncol(fc$counts))
        for (i in seq_len(ncol(fc$targets))) {
            ...
            resultlist[[i]]  <- restmp[[1]]
            ts[[i]] = restmp[[2]]
        }

  The 'copy-and-append' pattern is used, and should be avoided,
  elsewhere in the code. Likewise, 1:... is used elsewhere, and should
  be avoided.
- Use `message()` (printing to stderr) rather than `cat()` (printing
  to stdout) to report messages to the user; think about an R
  scripting environment and consider simple rather than highly
  decorated (e.g., `printParam()`) output.
- consider formatting your code using the [formatR][] or similar
  package, so that others, including your users, can easily parse it.
- do NOT include `library()` statements in R files; these packages
  should be made available using `Imports:` in the DESCRIPTION file,
  and `import: ggplot2`, etc., in the NAMESPACE file.
- All functions should return useful values, perhaps invisibly. For
  instance, `plotsamExplorer()` could return `invisible(fn)` or `pgg`
  (it would then not be necessary to call `plot(pgg)`, and the plot
  would be available for further user customization).

man

- samExplore.Rd: the \examples section contains text

        \examples{
        ## Not run:

  This has no effect other than to confuse the user -- the code chunk
  is evaluated.
- use `system.file(testdata, "Test1.sam", package="samExploreR")` or
  `file.path(infp, "Test1.sam")` rather than `paste()`
- indent the example section like code, e.g., the final continuation
  line should be indented
  
        res3 <- samExplore(inpf, N_boot=10, subsample_d=.8,
            countboot="Assigned")

- In the data documentation modules, e.g., `df_sole.Rd`, provide a
  description of the _meaning_ of the data in each column, in addition
  to the type of data.

inst

- Do not replicate data that is already available in Bioconductor,
  e.g., `hg19_RefSeq_exon.txt` is `system.file(package="Rsubread",
  "extdata", "hg19_RefSeq_exon.txt")`
- Re-use similar data from other packages rather than introducing
  large data objects, e.g., use Rsubread/inst/extdata/reads1.txt.gz or
  [RNAseqData.HNRNPC.bam.chr14][]

[RNAseqData.HNRNPC.bam.chr14]: http://bioconductor.org/packages/RNAseqData.HNRNPC.bam.chr14
[formatR]: https://cran.r-project.org/package=formatR

**Comment by shaileshtripathi** [comment]
Hi Martin,

The changes on package which you have suggested have been made.
Looking forward to finalize the review of the package.

Best,
Shailesh

**Comment by mtmorgan** [comment]
## New comments

Please replace this with your intended content

    \begin{verbatim}
    Remark: To be added after uploaded to Bioconductor.
    \end{verbatim}
    
When I run

    cd samExploreR/vignette
    R CMD Stangle 
    R -f Manual.R
   
I see the following warnings, which are usually a sign of a
programming error

    Warning messages:
    1: In ts[i] <- c(ts, restmp[[2]]) :
      number of items to replace is not a multiple of replacement length
    2: In ts[i] <- c(ts, restmp[[2]]) :
      number of items to replace is not a multiple of replacement length
    3: In ts[i] <- c(ts, restmp[[2]]) :
      number of items to replace is not a multiple of replacement length

## Previous comments

The following issues were not addressed:

NEWS

- either populate with content that can be parsed by news() (see,
  e.g., GenomicRanges/NEWS) or remove
  
vignettes

- the standard latex packages enumitem.sty, sectsty.sty, and
  verbatim.sty are not needed

- carefully consider the need for additional latex sty files included
  in the preable

- Use the markup `\Rcode{}` rather than LaTeX math $samExplore$ for R
  functions.
  
  - e.g., exploreRob, line 170; exploreRep, line 200

- The call to `plotsamExplorer()` generates a note that seems like it
  should be avoidable, an

        > plotsamExplorer(df_intersect,font.size=3, anova=FALSE)
        Scale for 'fill' is already present. Adding another scale for 'fill', which will
        replace the existing scale.

R

- ...Likewise, 1:... is used elsewhere, and should
  be avoided.
  
  - use `seq_len()` or `seq_along()`

- Use `message()` (printing to stderr) rather than `cat()` (printing
  to stdout) to report messages to the user; think about an R
  scripting environment and consider simple rather than highly
  decorated (e.g., `printParam()`) output.

    - still used in plotdat.R

man

- In the data documentation modules, e.g., `df_sole.Rd`, provide a
  description of the _meaning_ of the data in each column, in addition
  to the type of data.

inst

- Re-use similar data from other packages rather than introducing
  large data objects, e.g., use Rsubread/inst/extdata/reads1.txt.gz or
  [RNAseqData.HNRNPC.bam.chr14][]
  
  - Here I mean extdata/Test*.sam

[RNAseqData.HNRNPC.bam.chr14]: http://bioconductor.org/packages/RNAseqData.HNRNPC.bam.chr14
[formatR]: https://cran.r-project.org/package=formatR

**Comment by shaileshtripathi** [comment]
Hi Martin,

I fixed those issues, but now package is not compiling for mac system
(error in creating vignette), it was not happening before
Do you think it is some error related to bioconductor server, it do compile
it on my system and it is doing fine

Best,
Shailesh

**Comment by mtmorgan** [comment]
It is a build system problem and should be ignored.

**Comment by shaileshtripathi** [comment]
@mtmorgan : Hi Martin wondering if the package is fine now, it already a lot of time, I spent for the package.

**Comment by mtmorgan** [comment]
Aargh, why are previous issues still not addressed?

- ...Likewise, 1:... is used elsewhere, and should
  be avoided.

        samExploreR/R$ grep "1:" *
        featureCounts.R:    for (i in 1:length(fc$targets)) {
        featureCounts.R:    for (i in 1:N_boot) {
        plotdat.R:    hcl(h = hues, l = 65, c = 100)[1:n]
        plotdat.R:        for (i in 1:length(grp)) {
        plotdat.R:        for (i in 1:lenfactor) {
        plotdat.R:        for (i in 1:lenfactor) {
        plotdat.R:            # print(tt) for(j in 1:length(dpth)){
        
- carefully consider the need for additional latex sty files included
  in the preable -- are these all really needed???

        vignettes$ grep usepackage *Rnw
        \usepackage{makeidx}  % allows for indexgeneration
        \usepackage[dvips]{graphicx}
        \usepackage{dsfont}
        \usepackage[utf8]{inputenc}
        \usepackage{amsmath}
        %\usepackage{bbb}
        \usepackage{Sweave}
        \usepackage{epsfig}
        \usepackage{color}
        \usepackage{psfrag}
        \usepackage{sectsty}
        \usepackage[english]{babel}
        \usepackage{rotating}
        \usepackage{rotate}
        \usepackage{lscape}
        %\usepackage{stmaryrd}
        \usepackage{eufrak}
        \usepackage{bbm}
        \usepackage{marvosym}
        \usepackage{txfonts}
        \usepackage{pgf}
        \usepackage{tikz}
        \usepackage{tikz}
        
Note that for these the use of paste() is (mostly?) not needed

    R$ grep message *
    featureCounts.R:        message(paste("Sub sampling: ",fc$targets[i],"\n", sep=""))
    featureCounts.R:        message(paste("Sub sample N: ", i, "\n", sep = ""))
    featureCounts.R:    message(paste("Simulated Depth: ", depth * 100, "%", "\n", sep = ""))
    featureCounts.R:    message(paste(" Number of sub samples: ", boot, "\n", sep = ""))
    plotdat.R:        message(fn)
    plotdat.R:        message(paste("\n file is saved as", fn, "\n \n"))
    samtest.R:    message(paste("ANOVA test for label '", lbl, "' and f values ", paste(as.character(f_vect), 
    samtest.R:    message(paste("ANOVA test for labels '", paste(as.character(lbl_vect), collapse = "', '"),

**Comment by shaileshtripathi** [comment]
Hi Martin,

I submitted changes for samExploreR, could you please review it again.

Best,
Shailesh

**Comment by mtmorgan** [comment]
Thank you for your responses to the review. I am happy to mark your package as accepted. It will be processed to the Bioconductor svn repository and nightly 'devel' builds; more information will be available in the next few days.
