### ISSUE TITLE
phemd

### ISSUE THREAD

**Issue by wschen** [Bioconductor/Contributions#897]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wschen/phemd

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Please update your package to interoperate (i.e., accept as inputs) with the SingleCellExperiment and / or SummarizedExperiment objects, and other relevant [core Bioconductor classes][2]

[2]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by wschen** [comment]
> Please update your package to interoperate (i.e., accept as inputs) with the SingleCellExperiment and / or SummarizedExperiment objects, and other relevant [core Bioconductor classes](http://bioconductor.org/developers/how-to/commonMethodsAndClasses/)

**Comment by wschen** [comment]
I have tried to force the use of a prior version of a package (VGAM 1.0-5) as one of the functions was removed in the latest update of the package but the auto-builder does not seem to be allowing this. This is a known requirement for one of the packages that my own package is based on and their recommended workaround is what I performed. Is there a way to test the build outside of this? I am able to build successfully using my own version of R with VGAM 1.0-5.

https://github.com/cole-trapnell-lab/monocle-release/issues/211
https://github.com/cole-trapnell-lab/monocle-release/issues/188

**Comment by LiNk-NY** [comment]
Hi William, @wschen 
We strongly discourage the use of a single version of a package as a dependency (`VGAM = 1.0-5`).
This seems to be an issue for the `VGAM` maintainer(s). 

If your package does not work with future versions of `VGAM`, I suggest that you find an
alternative set of package, if possible.

Regards,
Marcel

**Comment by wschen** [comment]
@LiNk-NY I have addressed all errors and most warnings. The remaining warning is due to a "set.seed" call that I make in a function to ensure reproducibility of results from repeated runs (at a step of random subsampling of data for downstream analyses). I believe that this is preferable to the user but please let me know if you have another solution or recommended change. 

Also, is there a specific course of action that I should take to request code review for package acceptance into BioConductor's next release?

**Comment by LiNk-NY** [comment]
Hi @wschen,
I will be reviewing your package. We review them as a first-come-first-serve basis.
There are other packages that were submitted before yours.

Thank you.

**Comment by LiNk-NY** [comment]
Hi William, 
Thank you for submitting to Bioconductor.
I've reviewed your package. 

If you have any questions, please respond as a comment to the issue. 
Thank you,
Marcel

---

# phemd #897

## DESCRIPTION

* Please use the full `R.version` string `3.5.0`
* `SingleCellExperiment` or `SummarizedExperiment` not in `Imports`. If you're
going to support these data classes, you should be importing the necessary
functions to make interoperability possible (`assay`).
* Format the file to not exceed 80 column width

## NAMESPACE

* Class names are capitalized by convention. You may also want to remove
('obj') suffix from the name.
* The Bioconductor convention is to use `camelCase` instead of `snake_case`

## vignettes/

* Please use a more descriptive title
* Consider using `BiocStyle::html_document` for the vignette build
* Remove any mention of `biocLite` and replace it with `BiocManager::install`
* Remove any commented code that is not running.
* Stay within the 80 width column limit so that maintaining your vignette and
code becomes easier.

## R/

* When working with `data_list` in `get_sample_sizes`, it is better to use
`vapply(data_list, nrow, integer(1L))` rather than an allocate-and-fill `for`
loop
* Remove all instances of semi-colons `;` as they are not necessary.
* Consider using a vector of options as the default argument for `cell_model`
and subsequently using `match.arg` to default to the first or the entered
option.
* Avoid using a `for` loop for splitting data, just use `split` (see
`ref_clusters`)
* Use arrow `<-` for assignment instead of equals sign `=`
* Use `lapply` and `*apply` family to work with `lists`, it saves from
`for` loop object management (for example see `indentify_centroids`)
* Avoid using `eval(substitute(...))` for NSE, in `gaussianff_local`, you can
just first calculate the arguments for the new `vglmff` class ('constraints',
'deviance', etc.) and then use those outputs as inputs to the `new` function.
* Please see the Bioconductor best practices guidelines: 
http://www.bioconductor.org/developers/package-guidelines/#rcode
* Avoid using `1:M` etc.
* Replace `attach` with another verb in `attach_seuratobj` (e.g., `bindSeurat`)
* Please make accessor and setter functions for your object class for example,
`seuratInfo(phemdObject)` and `seuratInfo(phemdObject) <- seuratObject`.
* Avoid using `@` to access slots
* Provide validity checks for the `phemdObj` class to increase robustness.
* Import the `isEmpty` generic in `S4Vectors` to create a method for your
`phemd` class.
* Plotting functions should not save to the user's file system by default,
that can be done by the user's invocation of `pdf`, `png` or another desired
file format.
* Separate `methods.R` into different files such as `plotting.R` and other
files so that they are easier to manage.
* Avoid saving intermediate files without the user's consent (`dm.RData`)

**Comment by LiNk-NY** [comment]
Hi William, @wschen 
Thanks for making those changes. 
I will accept your package.

Please use the diff below to stay within the 80 character limit. 

Also, a few things to work on after the release: 

* Remove the class check `is(obj, "Phemd")` from method function definitions. The method
only gets dispatched on the class so the test is not necessary. 
* Minor: Use `S4Vectors::setValidity2` to display cumulative issues with class validity rather
than fail and report for a single issue (current set up). 

Best regards,
Marcel
---

```diff
diff --git a/DESCRIPTION b/DESCRIPTION
index f35c520..6af0e41 100644
--- a/DESCRIPTION
+++ b/DESCRIPTION
@@ -4,13 +4,45 @@ Title: Phenotypic EMD for comparison of single-cell samples
 Version: 0.99.20
 Author: William S Chen
 Maintainer: William S Chen <wil.yum.chen@gmail.com>
-Description: Package for comparing and generating a low-dimensional embedding of multiple single-cell samples.
+Description: Package for comparing and generating a low-dimensional embedding
+  of multiple single-cell samples.
 License: GPL-2
 Encoding: UTF-8
 LazyData: true
 Depends: R (>= 3.5.0), monocle
-Imports: SingleCellExperiment, RColorBrewer, igraph, transport, pracma, cluster, Rtsne, destiny, Seurat, RANN, ggplot2, maptree, pheatmap, scatterplot3d, VGAM, methods, grDevices, graphics, stats, utils, cowplot, S4Vectors
+Imports:
+  SingleCellExperiment,
+  RColorBrewer,
+  igraph,
+  transport,
+  pracma,
+  cluster,
+  Rtsne,
+  destiny,
+  Seurat,
+  RANN,
+  ggplot2,
+  maptree, pheatmap,
+  scatterplot3d,
+  VGAM,
+  methods,
+  grDevices,
+  graphics,
+  stats,
+  utils,
+  cowplot,
+  S4Vectors
 Suggests: knitr
 VignetteBuilder: knitr
-biocViews: Clustering, ComparativeGenomics, Proteomics, Transcriptomics, Sequencing, DimensionReduction, SingleCell, DataRepresentation, Visualization, MultipleComparison
+biocViews:
+  Clustering,
+  ComparativeGenomics,
+  Proteomics,
+  Transcriptomics,
+  Sequencing,
+  DimensionReduction,
+  SingleCell,
+  DataRepresentation,
+  Visualization,
+  MultipleComparison
 RoxygenNote: 6.1.0
```

**Comment by wschen** [comment]
@LiNk-NY Thank you! I have updated the DESCRIPTION file and will update those couple of remaining minor edits soon.

**Comment by LiNk-NY** [comment]
Hi William, @wschen 

It looks like you didn't apply the diff. You should add two spaces in the
second line of the `Description` field. 
Please do that and bump the package version. 

-Marcel

**Comment by wschen** [comment]
@LiNk-NY Sorry about that – should be correct now!

**Comment by LiNk-NY** [comment]
Hi William, @wschen 
It doesn't look like you've removed the `is(obj, "Phemd")` calls. 
Please do so and don't forget to bump the version. 
Thanks,
Marcel

**Comment by wschen** [comment]
@LiNk-NY I've removed those calls from the method functions!

**Comment by LiNk-NY** [comment]
Hi William, @wschen 
Thanks for making those changes. 
Your package may be taking a bit too long to check. If possible, please simplify the
examples. 
Also, please avoid `if` condition checking on a vector: 
```r
Found the following possibly unsafe calls:
Warning in if (e3 == "asNamespace") e3 <- as.character(e[[4L]][[2L]]) :
  the condition has length > 1 and only the first element will be used
Warning in if (e3 == "asNamespace") e3 <- as.character(e[[4L]][[2L]]) :
  the condition has length > 1 and only the first element will be used
File 'phemd/R/functions-plotting.R':
  assignInNamespace(x = "draw_colnames", value = "drawColnames45", 
    ns = asNamespace("pheatmap"))
  assignInNamespace(x = "draw_colnames", value = "drawColnames45", 
    ns = asNamespace("pheatmap"))
```
Use `identical` or `all.equal`. 

Regards,
Marcel

**Comment by wschen** [comment]
@LiNk-NY Thanks for this suggestion. Since the functions in my package are all meant to be run sequentially, I could not shorten the examples but I have asked that R not check a few of the examples which involve (relatively simple) saving of plots or results. Note that these examples were checked successfully in a prior builds without problems or timeout on Linux and OS X and should work properly.

Regarding the "if" vector checking – that warning actually comes from the "asNamespace" function which is an R built-in. As a result, I cannot modify the code but I believe I am calling the function properly and it should not cause any problems despite the warning.

Best,
Will

**Comment by wschen** [comment]
@LiNk-NY I will work on the shorter examples and remove the save option from plotting functions.

Meanwhile, I am still unsure how to remedy the e3 == "asNamespace" call. From what I can tell, this 'e3 == "asNamespace"' check is performed by the R build / check process and is definitely not code that I wrote so I am unable to change it. A quick search online brought me to this source file (under the .check_package_code_tampers function):

http://mtweb.cs.ucl.ac.uk/mus/bin/install_R/R-3.1.1/build/src/library/tools/all.R

If using the "assignInNamespace" function is not allowed (which I am fairly confident is the ultimate culprit of this function call), I can remove this functionality from my package altogether (or open to other suggestions as to how to address this).

Thanks,
Will

**Comment by LiNk-NY** [comment]
Hi Will, @wschen 
You're right. My apologies.
I think the use of `assignInNamespace` is triggering that. 
Could you avoid using that function? 

Also, you have a number of undefined global variables: 
```
Undefined global functions or variables:
  assay assayData assays estimateDispersions estimateSizeFactors exprs
  featureData featureData<- pData phenoData seqlen seurat.combined
  varLabels<-
```
Please import the appropriate package(s) and functions such as `Biobase`.

**Comment by wschen** [comment]
@LiNk-NY No problem, glad we've figured that out. Unfortunately I don't know of a way around that function as it modifies one small part of a CRAN heatmap plotting function to make the heatmap marker labels much more readable. It is theoretically possible to exclude this altogether although I think the functionality as I've implemented it currently is beneficial for the user and downstream viewers.

I will look into importing the appropriate packages for those global variables as well.

**Comment by LiNk-NY** [comment]
Hi William, @wschen 
You could try contacting the maintainer and asking to let users provide
`hjust` and `rot` parameters in the main function. This will avoid you from replacing the function
in the package namespace. 
Best regards,
Marcel

**Comment by wschen** [comment]
@LiNk-NY Thanks for the suggestion. I have contacted the `pheatmap` maintainer and am awaiting a reply now. I am also still addressing the other changes you suggested and hope to resubmit an updated version soon.

**Comment by LiNk-NY** [comment]
Hi Wiliam, 
Could you provide further updates on the status of the `phemd` package? 
Best regards,
Marcel

**Comment by wschen** [comment]
@LiNk-NY I have addressed the issues we discussed as follows:
1. Removed "dontrun" tags from examples for all exported functions
2. Removed "save" functionality from all plotting functions as requested
3. Removed all calls to assignInNamespace – I have gotten an update from the pheatmap maintainer who has updated the package to allow for rotation of the column labels. This has not yet been reflected in the CRAN repository but has been updated on the package Github page and will be reflected in CRAN soon. My function allows for the additional parameter to be passed into the pheatmap plotting function.
4. Imported all packages so that there should no longer be any undefined global functions or variables.

A remaining automatic "warning" is due to a single "set.seed" call which is important so that users can generate reproducible results. Another "warning" is due to my package requiring R version >= 3.5.0 instead of >= 3.6.0 – but doing so causes the build to fail on tokay2 (so I kept the requirement as R version >=3.5.0 for now). I hope these changes are sufficient for my package to be accepted!

Thanks,
Will

**Comment by wschen** [comment]
@LiNk-NY Just wanted to make sure you saw my latest message above the last couple of bot comments. Please let me know what you think when you get a chance.

Best,
Will

**Comment by LiNk-NY** [comment]
Hi William, @wschen 
Thanks for following up.
* I strongly recommend that you do not set any seeds inside functions. 
For users to ensure reproducibility, they should set the same seed **outside** the
function when sharing code.
* I still see a lot of `dontrun` tag in `R/Phemd-methods.R` and associated `man` pages.
Please remove them and provide a runnable example so that you don't potentially get
stale code.

Almost there! 
Thanks, 
Marcel

**Comment by LiNk-NY** [comment]
Hi William, @wschen 
Any updates on making the requested changes to the package? 
It is almost ready to be accepted. 

Best regards,
Marcel

**Comment by wschen** [comment]
@LiNk-NY I have updated the examples so that they should all be run now. I have also updated the function to allow for an optional seed to be passed in as a parameter and have documented it clearly in the man page. I think this is preferable for the specific use case I'm implementing – hope this is ok!

- Will

**Comment by LiNk-NY** [comment]
Hi William, @wschen 

Setting a default seed value is not the way to ensure reproducibility.

Users wishing to obtain reproducible results would create a script and
set their own seed within the script and not inside the function. 

Please remove the `set.seed` function from your code. 

Regards,
Marcel

CC: @mtmorgan

**Comment by mtmorgan** [comment]
The user expects that
```
set.seed(123)
your_function()
rnorm(1)
```
will produce different results than
```
set.seed(234)
your_function()
rnorm(1)
```
but if `your_function()` does `set.seed(345)` then their attempt is thwarted.

On the other hand if they'd like to implement reproducibility for your function, then they would be able to
```
set.seed(456)
your_function_without_set_seed()
```

So there is nothing to be gained by setting the seed inside your function, and much frustration to be introduced.

**Comment by wschen** [comment]
@LiNk-NY Got it, removed the set.seed call inside the function!

- Will

**Comment by LiNk-NY** [comment]
Hi William, @wschen 
Thanks for making that change. 
Please resolve the errors in the `aggregateSamples` function examples:

```
> my_phemdObj_lg <- aggregateSamples(my_phemdObj_lg, max_cells=1000, cur_seed=112)
Error in aggregateSamples(my_phemdObj_lg, max_cells = 1000, cur_seed = 112) : 
  unused argument (cur_seed = 112)
Execution halted
```
This is due to the recent change. 

Best, 
Marcel

**Comment by wschen** [comment]
@LiNk-NY Sorry about that, fixed now!

**Comment by LiNk-NY** [comment]
Hi William, @wschen 
Please resolve the BiocCheck warnings:

```
* Checking R Version dependency...
    * WARNING: Update R version dependency from 3.5.0 to 3.6.
```

**Comment by wschen** [comment]
@LiNk-NY Hi Marcel, I've updated the R dependency as requested.

Thanks,
Will

**Comment by LiNk-NY** [comment]
Hi Will, @wschen 
Thank you for making those changes!
Your package has been accepted. 
Best regards,
Marcel

**Comment by wschen** [comment]
@LiNk-NY Thanks!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wschen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("phemd")`. The package 'landing page' will be created at

https://bioconductor.org/packages/phemd

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
