### ISSUE TITLE
Celda Submission

### ISSUE THREAD

**Issue by definitelysean** [Bioconductor/Contributions#910]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/compbiomed/celda

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dvantwisk** [comment]
Hello,
Just a reminder that the deadline for packages to be accepted for the 3.8 release is October 24th. I will work to try to get a review to you asap, but before that the package needs to build correctly.

**Comment by definitelysean** [comment]
Hi Daniel,
Thanks very much for the reminder. I should have the remaining errors and
warnings resolved in the next day or two.
One error we keep getting is that the package maintainer isn't subscribed
to the devel list, though everyone mentioned in our DESCRIPTION has assured
me they're subscribed. Is there a way to check which person is not
subscribed?

**Comment by dvantwisk** [comment]
It seems that Joshua Campbell's email, `camp@bu.edu`, is not on the mailing list. There is a verification email to register to the list. Maybe he hasn't verified his account?

**Comment by dvantwisk** [comment]
Can you perform a version bump?

**Comment by definitelysean** [comment]
Done. I understand that, due to the GitHub outages over the past 24 hours,
a lot of webhooks aren't being triggered -- hopefully the Bioconductor
build will be kicked off.

**Comment by dvantwisk** [comment]
I wasn't aware of that. I follow up if there's an issue.

**Comment by dvantwisk** [comment]
If the user wants reproducibility, it is best for them to use `set.seed()` as opposed to the package invoking it. Often a user might wish to set different seeds for their own purposes; if the developer uses `set.seed()` then it undermines the ability of the user to do this. For that reason, we must insist the the set seed is removed and that the user be given the option to include their own seed. I will look over your package now since the deadline for the bioc3.8 release is looming, but this `set.seed()` must be corrected.

**Comment by dvantwisk** [comment]
I've reviewed your package. It looks very well written but I have a few issues that I need you to address. [REQUIRED] tags must involve making the change or addressing it. [CONSIDER] tags are changes that are advisable but not required. I would still like you to modify the way your package takes seeds and requested before.

The Bioconductor 3.8 release deadline is coming up and we can still get your package in as long as it is all complete by Tuesday October 30th. It would be better to have everything done earlier just in case some stubborn errors/warning arise on the build system.

Please message me when you are finished making changes.

GENERAL
- [CONSIDER] Using `BiocParallel` in place of `parallel`.
- [CONSIDER] Use `seq_len()` or `seq_along()` in place of `1:...`. Doing this
is slightly more efficient.
- [REQUIRED] It seems that you are using the s3 class system in this package
for classes like `celda_C` and using s3_dispatch on methods declared in
`s3_generics.R`. Is this correct? The issue is that Bioconductor requires that
the s4 class system be used for user facing class and methods. Please convert
these to use the s4 dispatch.
https://www.bioconductor.org/packages/release/bioc/vignettes/S4Vectors/inst/doc/S4QuickOverview.pdf
https://kasperdanielhansen.github.io/genbioconductor/html/R_S4.html 
- The package is 112MB in size. We generally want to see pacakges that are at
most 5MB. It seems that your `.git` directory is 109MB, indicating that you
likely committed some large files and later deleted them. Please use the BFG
Repo-Cleaner in order to reduce the size of the `.git` directory as much as
possible:
https://rtyley.github.io/bfg-repo-cleaner/

R/StateHeatmap.R
- [REQUIRED] L40-43: The copy-and-append pattern we see here is very
inefficient. This is because declaring `feature.indices` as an empty vector
and then iteratively adding to it with a for-loop requires a new vector of
extra length to be created and the elements in the old vector to be moved to
the new one. One can make this process more efficient be preallocating the 
vector e.g. `feature.indices <- vector(mode = "integer", length = <known_length>`.
This will remove the need to iteratively create and move the elements to a new
vector. A better way in this case would be to just use `vapply()`:
```
feature.indices <- vapply(feature.module, function(module) {
    top.rank$index[[module]]
}, integer(1))
```
(It may be prudent to use `lapply()` then `unlist()` if the returned vector
length is variable.)

R/celda_G.R
- [REQUIRED] L651-654: Use `vapply()` to declare `feature.grep`.
- [REQUIRED] L657-663: Use `lapply()` to declare `list`.

R/celda_functions.R
- [REQUIRED] L213-216: Use `vapply()` declare `new.hsv`.

R/data.R
- [CONSIDER] Added documentation with regards to the source and dimensions of
the data.

R/initialize_clusters.R
- [REQUIRED] L151: It looks like you are just initalizing `ll` here. Just use
`ll <- vector(mode = 'numeric', length = ncol(temp.y))`. There are other
places where you use `rep()` to initialize a variable where it seems that just
using `vector` would suffice. Just using `vector` will run faster.

R/model_performance.R
- [REQUIRED] L40-43: Use `lapply()` to declare `countsList`.

R/split_clusters.R
- [REQUIRED] L15-19: Use `lapply` to declare `clust.split` 
- [REQUIRED] L48-78, 140-170, 260-291: The `pairs` argument is iteratively made
by repeated calling `rbind` in a double for-loop. This seems inefficient and can
probably be corrected by using nested `lapply()` loops to create a list of lists
of `c(i, j)` pairs and then calling `rbind` with
`pairs <- do.call(rbind, pairs_list)` to instantiate `pairs`.

vignettes
- [REQUIRED] Using `eval=FALSE` in vignette code blocks is generally not
accepted since this code is user facing and must be able to run. For this
reason it should be built on the build machines. It seems that the reason you
did this was to display graphs that you have in your vignettes directory. Is
it possible to run this code and display the graphs that they generate instead
of displaying the image of the graph? The calls to `library()` and `help()` can
be surrounded by `eval=FALSE`.

**Comment by joshua-d-campbell** [comment]
Hi @dvantwisk, thank you for your in-depth and thorough review of our package as well as the helpful suggestions for improving efficiency and quality. We should have most of them implemented very soon. One small issue is related to the vignette figures and setting eval=FALSE for some pieces of code. Some clustering functions take a little bit of time since they are using MCMC sampling, even on a relatively small dataset. In order to bring the whole package under the build time requirements, we saved the output of those commands as a figure and then just display the figure while not actually executing the original code. We are not really sure of another way to do this while maintaining a relatively meaningful size example dataset.

The other larger issue we are still internally struggling with is how to deal with the ‘set.seed’ calls for the initialization of the Gibbs sampling/EM algorithms. There seem to be two opposing forces: on the one hand, calling set.seed may potentially influence workflows where it will be important to precisely control the randomization. On the other hand, not setting the seed will mean that the exact results from our clustering algorithms will be irreproducible _**by default**_. In this second setting, the only way to maintain reproducibility is to (A) have the user remember to set the seed beforehand each time they call the algorithm or (B) to have the user remember to save the results object which contain a copy of the seed.

Related to part A, one of our goals is to make the package “user-proof” by minimizing the number of ways they can inappropriately apply the algorithm or misinterpret the results. Many users will be entry-level Bioinformatics analysts that are quickly trying to gain biological insights from new datasets. They will be running the algorithm several times with different parameters and/or pre-filtering steps. If they forget to set the seed, then they will have to re-run everything up to the last point where the seed was set, which can take a fairly large amount of time. If the seed was not set at all, then they may not be able to recover their results at all. Even if we clearly document and highlight the need to set the seed every time, we are worried that the users will accidentally forget to do it quite often. Being able to apply the same code and get the same results is something we believe our users will prefer to have happen automatically so it is one less thing they have to keep in mind and one less source of error. Related to part B, even if the user remembers to save the results object, there is still quite a bit of complexity in trying to recoup and apply the correct seed for recapitulating analyses. We implement multiple chains that each have a different random starting point. However only the best chain is usually kept. In order to know how the set of seeds were created for all chains, the initial seed needs to be known. However, to recapitulate an individual chain, that specific seed needs to be known and applied.  

We are trying to figure out how to balance these opposing forces and have two potential thoughts: (1) We could allow the user to set the ‘seed’ argument to NULL and then the calls to ‘set.seed()’ will be bypassed with ‘if’ statements. This would allow an advanced user the option and flexibility to deactivate seed setting for the (likely rare) workflows that require this precise control. A user that will want to perform this level of advanced analysis will also be generally be advanced enough to understand, handle, and record ‘set.seed’ manually. (2) Another option is to use the “dqrng” package for random seed generation so we do not change R’s internal .Random.seed variable. We will document that fact that the randomization for other packages using “dqrng” may be affected. 

If it is a “hard and fast” rule for Bioconductor to not allow calls to ‘set.seed’ or not use dqrng for seed setting, we definitely understand the reasoning. However, we are so concerned about this issue of “reproducibility by default” we are worried that we may not be able to move forward with the submission. 

Again, thanks for your substantial time commitment and thoroughness in reviewing the package. We are looking forward to getting your thoughts.

**Comment by dvantwisk** [comment]
Thank you for the explanations.

For the `eval=FALSE`s, the issue is still that this code that you are saying the user should be able to run isn't being tested by the build machine. If some part of the code were to go awry for any reason, you wouldn't know about it unless a user were to bring it up to you. Is it possible for the package to build in time on even a minimum example that covers the functionality of the code in your vignette?  i.e. for all functions/methods you display as runnable by the user in the vignette, can we get a minimum example that our build machines can run to ensure that these functions/methods can work?  I am seeing that your `tests` directory do include tests for many of them. Is it true for all of them? And although this still wouldn't ensure all functionality that you are promising the user in the vignette, it should make things acceptable.

With regards to the `set.seed()` issue, I currently do not have a statement about the `set.seed()` issue. It is an issue that we normally do not face. I've asked some of my colleagues about it and hopefully will have an answer about it very soon. In the meantime, I suggest you work on the other changes that are not related to this issue.

**Comment by dvantwisk** [comment]
Your option (1) of dealing with this issue seems acceptable. We can ignore the warning on the build system that this will generate.

**Comment by definitelysean** [comment]
Hi @dvantwisk , our team has decided not to submit our package for the upcoming Bioconductor release. We are in progress implementing the changes you specified, but for the sake of ensuring our code will be stable, we think we'll need extra time for this process. 

Thank you very, very much for your  thorough review of our code and for your insightful feedback. We will create a new submission for the April release as soon as we decide the package is in good shape; hopefully at that time, we can work together again on including celda in Bioconductor.
