### ISSUE TITLE
DepecheR

### ISSUE THREAD

**Issue by Theorell** [Bioconductor/Contributions#972]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Theorell/DepecheR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Theorell** [comment]
Thank you!

**Comment by mtmorgan** [comment]
It seems like you'd like to choose classes and conventions as inputs / outputs that facilitate interaction amongst Bioconductor packages. Please try to identify and support [common classes][1] for use in the interface to your package.

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by Theorell** [comment]
Dear MtMorgan, 
Thank you for your attention. We have been discussing this, but have abstained from it so far, as this package fits into multiple possible BioConductor workflows. I am primarily thinking about the SingleCellExperiment and the flowSet classes and the connected analysis pipe lines. Would it suffice to add a function taking a SingleCellExperiment object or a flowSet and returning the suitable format for DepecheR? 
Best regards 
Jakob

**Comment by Theorell** [comment]
@mtmorgan The original path to the repository that was posted here was slightly wrong: it should have been Theorell/DepecheR, not theorell/DepecheR. I have edited the original comment, and hope that the coming pushes will work with the web hook I have created. Once you have aknowledged this change, I will bump the version in the repository, to hopefully trigger a new build.

**Comment by lshep** [comment]
The repository name has been updated on our end. Thank you for letting us know.  If your webhook is active it should produce build reports.  If you feel like you are doing a version bump but do not receive a build report please leave a comment and tag (@lshep)  else @mtmorgan / @nturaga can continue on with addressing any other comments/questions with your formal review.  Cheers.

**Comment by jtheorell** [comment]
@Ishep I am not so sure it is the only reason... Also made a  misstake. Thank you anyhow!

**Comment by lshep** [comment]
ok!   My updates are complete so you should be able to develop as normal now.  Cheers

**Comment by jtheorell** [comment]
Dear @mtmorgan and @nturaga, 
Now it seems to pass the same way as it does on our machines. Neither me or @Theorell are normally running Windows, however, and it seems like the testthat tests are considerably slower on that system than on the Linux-based ones (179s/174 s instead of 32s/80s or 34s/91s). Is this system-specific speed issue a problem for the review process? If so, is there some doable workaround for it? I have tried to look some now, but have not found any, but that might just be ignorance on my side.
Best 
Jakob Theorell

**Comment by jtheorell** [comment]
Hello @lshep, @mtmorgan and @nturaga, 
I wonder how we can proceed from here. I have also added a question to the email list a few days ago, but have not gotten any answer. Excited to move things forward. Any suggestions? Can we leave the slow test on Windows as it is for now?
Best regards
Jakob

**Comment by mtmorgan** [comment]
It's definitely unusual that the unit tests are that much longer, and the nightly build system (used once the package is accepted) has overall time limits so it is important to understand what the nature of the problem is.

What are the features of your unit tests? Do they use a lot of memory? I/O? Internet access?

**Comment by jtheorell** [comment]
Dear @mtmorgan, 
Thanks for your answer! In total, there are 11 test_that tests. Of these, three contain parallelized parts, but the test datasets are very small for these, so they are not that memory intensive. 
On top of this, there are a number of visualization function "tests" (mainly the examples from the package that we have put int he tests as well, to have a rapid way of testing that the whole package is functional). Some of these print quite a lot to screen (the main contributor to this is the mixOmics function tune.splsda). None of these take up especially much memory, but I read somewhere that printing could be an issue on Windows. Should I remove these "tests", that only run the user functions, that are redundant, as the examples will be run as well as part of the checks? 
Best 
Jakob

**Comment by mtmorgan** [comment]
Scanning your code briefly, it looks like you use detectCores() - 1 cores for parallel evaluation; the Windows machines have more cores than than linux / mac and so spawn more processes; I would suggest throttling number of cores in examples and unit tests to a very modest number, e.g., 2, so that your package is not contending for resources with other jobs, or with itself.

**Comment by nturaga** [comment]
@Theorell I'll review your package in the next 3 days.

**Comment by jtheorell** [comment]
@nturaga, 
Thank you very much! Looking much forward to your input!

**Comment by jtheorell** [comment]
Dear @nturaga,
Can I do anything to aid you in your review at this stage? 
Best regards
Jakob

**Comment by jtheorell** [comment]
Dear @nturaga, 
Now, it was 18 days ago that you said you would review the package within the coming three days. Are you still conducting the review, or are you waiting for me to do something? I am eager to proceed with this project. 
Best regards
Jakob

**Comment by nturaga** [comment]
# DepecheR review

## R CMD build

ok

## R CMD INSTALL

ok

## Build report

 * WARNING: R CMD check exceeded 5 min requirement (This can possibly
   with further builds, fix other issues before addressing this one)

 * Multiple NOTE entries in the build report, all of which are easily
   fixable.

## DESCRIPTION

* You don't need `Authors@R` and `Author`/`Maintainer` sections in the DESCRIPTION
  file. I would recommend keeping just the `Authors@R`.

* Add line wrapping and indent as needed (take for example
  https://github.com/Bioconductor/BiocParallel/blob/master/DESCRIPTION)

## NAMESPACE

* ok

## man

* ok

## vignette

* Please use `BiocStyle` for your vignette.http://bioconductor.org/developers/package-guidelines/#vignettes

## R

* Please fix your indentation of R code. Some of the lines are too
  long, some are not indented to make the code more readable. Use the
  package `formatR` if needed.

* No need to use the function `rm` to remove variables from memory. R
  does this automatically through garbage collection.

* For end user messages, use the priciples shown here,
  http://bioconductor.org/developers/how-to/coding-style/. You don't
  need `print` statements.

```
End-User messages

message() communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.
warning() communicates unusual situations handled by your code.
stop() indicates an error condition.
cat() or print() are used only when displaying an object to the user, e.g., in a show method.
```

* In `dColorPlot.R`, Do not use `setwd` or `getwd`, instead just get
  the file path, and create the directory where you need to write your
  plots. You can be assured that R always starts up in the working
  directory, you do not need to use `getwd`

  ```
  fpath <- "Plots"
  pdf(file.path(fpath, "palette.pdf"))
  ```

  You can avoid,

  ```
	  if (createDirectory == TRUE) {
		workingDirectory <- getwd() ## Never use
		dir.create(directoryName)
		setwd(paste(workingDirectory, directoryName,
			sep = "/")) ## Not needed
	}
  ```

* In `dColorPlot.R` and other functions if needed, please check the
  "type" of each argument at the very beginning of the
  function. `stopifnot()` is a good way to do this. You want to fail
  early if the user if not providing the correct input type.

```
stopifnot(
	is.logical(densContour),
	is.logical(addLegend),
	is.logical(drawColorPalette),
	....
	)
```

  You should do this instead of checking in at each if statement.

	```
	# Create the density matrix for xYData.
	if (is.logical(densContour)) { ## Not needed
		if (densContour == TRUE) { ## if(densContour) is the same as what you have
			densContour <- dContours(xYData)
		}
	}
	```


* You don't need to test for value `if (missing(x) == TRUE)` is the
  same as `if (missing(x))`. Replace this everywhere.


* Please use `BiocParallel::bplapply` instead of `foreach`, `snow`,
  `doSNOW` and `parallel` for parallel evaulation of parts of your
  code. You can replace large amounts of code in your package easily,

  ```
  if (multiCore == "default") {
			if (nrow(colorData) > 1e+05) {
				multiCore <- TRUE
			} else {
				multiCore <- FALSE
			}
		}
		if (multiCore == TRUE) {
			if( nCores=="default"){
				nCores <- floor(detectCores()*0.875)
				if(nCores>10){
					nCores <- 10
				}
			}

			cl <- makeCluster(nCores, type = "SOCK")
			registerDoSNOW(cl)
			i <- 1
			foreach(i = seq_len(ncol(colorVectors)),
				.inorder = FALSE) %dopar%
				dColorPlotCoFunction(colorVariable = colorVectors[,
				  i], name = names[i], xYData = xYData,
				  title = title, densContour = densContour,
				  bandColor = bandColor,
				  dotSize = dotSize, createPlot = createPlot)
			stopCluster(cl)
  ```

  vs

  ```
  param <- BiocParallel::MulticoreParam()  ## add configuration to MulticoreParam()
  bplapply(seq_len(colorVectors),
		   function(i) {
			   dColorPlotCoFunction(colorVariable = colorVectors[,i],
			   name = names[i], xYData = xYData,
			   title = title, densContour = densContour,
			   bandColor = bandColor, dotSize = dotSize,
			   createPlot = createPlot)
		   },
		   BPPARAM = param)

  ```

 Use `BiocParallel` everywhere and add that in your DESCRIPTION as
 well. Make the same changes and replace all parallel implemetations
 using other packages with BiocParallel.


* Your use of `any` seems not needed in most cases. Unless you expect
  to get back a vector of length > 1 of logical values, it is really
  not needed. You just need `is(x) == <class>`. Please fix as needed
  throughout your code.


* Instead of using a large number of `if` statements, try the `switch`
  case. Especially, in a function such as `dColorVector`, which can be
  written with greater ease.

```
colorScale  <- function(x, type) {
	switch(type,
		inferno = inferno(length(order)),
		viridis = viridis(length(order))
	..... ## and the rest
)
}
```


* This is not required, `seq_len(length(X))`. You can just use
  `seq_len(X)`. Please check for places you use this and correct it.

* Private functions which are not exported also need some
  documentation. (Your future self will thank you, also the reviewers).

* In the function, dOptPenalty.R, there are many magic numbers in your
  code. There is no documentation explaining why these numbers are
  used.

* Do not set `options` without resetting them to the original setting.


```
options(digits = 14) ## NEVER DO THIS
logCenterSd[[2]] <- inDataFrameScaleList[[2]]
options(digits = 7)
```


vs

```
old_opt <- options(digits = 14)
## Do stuff
options(old_opt)
```

* You can aggregater you helper functions into `dVoilinsCoFunctions.R`
  and put in `dViolinsCoFunction(1,2,3)` in them.

* Use vapply

```
	median1 <- 100 * apply(clusterFractionsForAllIds1,
		1, median)
	median2 <- 100 * apply(clusterFractionsForAllIds2,
		1, median)
```

or look even better option is to use `colMedian` in package `matrixStats` which is highly optimized.

* `paste` recycles vectors automatically,

```
directoryNames <- lapply(c(seq_len(length(aunique(depecheResultFirst$clusterVector)))),
			function(x) paste("Cluster",
				x, "level_two_depeche", sep = "_"))
```

vs

```
directoryNames <- paste("Cluster", 1:10, "level_two_depeche", sep="_")
```

Do this everywhere. A lot of the functions are already "vectorized" in
R, which you don't need to use in a loop. Make sure to read and use
the tips in here
http://bioconductor.org/developers/how-to/efficient-code/ throughout
your codebase.


## General

Consider this a first review of your package. Once you have corrected everything in this review, please leave a detailed reply of the corrections. Once that is done I will proceed with a secondary review.

Best,

Nitesh

**Comment by jtheorell** [comment]
Dear @nturaga, 
Thank you very much for all your invaluable comments, which have led to a clear improvement of the package. Below are point-by-point replies to all raised questions. A new version of the package has also been submitted where the changes have been incorporated. 

## Build report
* WARNING: R CMD check exceeded 5 min requirement (This can possibly
with further builds, fix other issues before addressing this one)
**This has accordingly not been adressed so far.**
* Multiple NOTE entries in the build report, all of which are easily
fixable.
**See below**

## DESCRIPTION
**Author/Maintainer section removed.**
**Line wrapping and indent corrected**

## vignette
* Please use BiocStyle for your vignette
**Done. I however have one problem here. Most of the functions in the package make graphs, etc. As I am required to have a certain percentage of functions that do not have eval=FALSE, and I also do not want to use the option createOutput = FALSE, it means that the vinjette building produces a large number of graphs. Will this be a problem when the vinjette building is actually included in the real build on BioConductor? In that case, what can I do to get around it? One option would naturally be to accept the warning induced by having too few functions run in the vinjette.**

## R
* Please fix your indentation of R code. Some of the lines are too
long, some are not indented to make the code more readable. Use the
package formatR if needed.
**The previous version was a result of applying formatR. As that did not help sufficiently, I have reindented all code by hand now, only helped by correct RStudio settings. Hope you find it ok. I think it is considerably better now, even if I still get significant numbers of wrong indentations, although I use the automatic 4-space-indentation in RStudio.**

**rm() removed from code**

**Print messages corrected to messages. One print warning changed to a warning, one print stop corrected to a stop.**

* In dColorPlot.R, Do not use setwd or getwd, instead just get
the file path, and create the directory where you need to write your
plots. 

**Done.**

* In dColorPlot.R and other functions if needed, please check the "type" of each argument at the very beginning of the function. stopifnot() is a good way to do this. You want to fail early if the user if not providing the correct input type.

**In this case, the reason for this syntax is that the user can either provide a densContour matrix, or specify TRUE or FALSE (this is used in five of the six plotting functions). I use is.logical in this way in four independent functions in the package, two of the others being in the dScale function, where the user can either specify TRUE or FALSE or values that they want to scale or truncate to. The fourth one is internal. Is this a problem? I have not done any changes to this part.**

* You don't need to test for value if (missing(x) == TRUE) is the same as if (missing(x)). Replace this everywhere.

**Done**

* Please use BiocParallel::bplapply instead of foreach, snow,
doSNOW and parallel for parallel evaulation of parts of your
code. 

**After some testing, I am reluctant to do this. These are the reasons:**
* **First of all, the reason for using SNOW is that it works on Windows as well. This is the reason we started using it in the first place, and migrated away from parLapply.**
* **I implemented bplapply with multicoreParam() for the function above with your code, and got the following error:**

'Error: 'bplapply' receive data failed: error reading from connection'

* **After managing to get bplapply woring with SnowParam() for one of the functions, I did some benchmarking compared to the current setup, and the speed is about half, even when the number of cores is capped to 6 with registerDoSNOW, as it is in SnowParam() on my system.**
* **And most crucially, in dOptPenalty, I register the cluster once and then run a while loop in which only a fraction can be parallelized and I only stop the cluster after the whole loop is finished. If I would have to start a new cluster in each round, then the computational time would go up most substantially and unnecessarily.**

**Considering all these issues, I need more motivation as to why I need to change away from the current setup. It might be worth noting too that I have done a few changes to the current parallelization setup after comments from MP Morgan himself (setting nCores as a parameter with a default of n-1 in systems up to 10 cores and 10 cores there above).**

* Your use of any seems not needed in most cases. 

**This was a result of a previous warning that I got from BiocChec. I realize now that the way to go is to look specifically for what I am after, like is.matrix(x)==FALSE. Done.**

* Instead of using a large number of if statements, try the switch
case. 

**Done in all places I could find. Neat solution!**

* This is not required, seq_len(length(X)). You can just use seq_len(X). 

**I am sure you think about exchanging seq_len for seq_along. seq_len only takes a single integer as an input. I have changed to seq_along for all vectors/lists, and continued with seq_len(ncol()) for matrices and data frames.**

* Private functions which are not exported also need some
documentation. (Your future self will thank you, also the reviewers).

**Some more documentation has been added to all private functions. In this work, a number of private functions have also been removed, as they were found to be too redundant.**

* In the function, dOptPenalty.R, there are many magic numbers in your
code. 

**Three magic numbers were found: 1450 and 20 and the different multiplication factors for the different while loop iterations. They are now hopefully sufficiently explained in the comments.**

* Do not set options without resetting them to the original setting.

**Changing these options were remnants from a failed attempt to solve an earlier problem which is no longer present, so this has been removed from all functions.**

* You can aggregater you helper functions into dVoilinsCoFunctions.R
and put in dViolinsCoFunction(1,2,3) in them.

**dViolins has been completely revised in the updated version of the package, as the old version had not been updated for too long.**

* Use vapply or look even better option is to use colMedian in package matrixStats which is highly optimized. 
**The use of rowMedians and colMedians has been increased in the updated version of the package.**

* Do this everywhere. A lot of the functions are already "vectorized" in R, which you don't need to use in a loop. 
 
**The example above updated accordingly. All apply functions and for-loops have been investigated with the vectorization option in mind, and vectorization has been used in all places where it was easy to see how (sadly, not that many, as it is primarily internal functions that are called with the loops).**

* Consider this a first review of your package. Once you have corrected everything in this review, please leave a detailed reply of the corrections. Once that is done I will proceed with a secondary review.

**Looking forward to the next round!**

**Best wishes**
**Jakob**

**Comment by nturaga** [comment]
# Update

## Vignette

* vignette doesn't render BiocStyle CSS. Please make sure you are
  using it the right way.

* The vignette should use smaller datasets. It's ok to have plots in
  the vignette, that is not a problem. Embed the graphs in your HTML
  vignette. This is done by a lot of packages, and should not be an
  issue. Do not use massive datasets, since it is software package,
  your total package size should be less than 5MB.


## R

* You don't need to check if a logical value is "TRUE" in your "if"
  statements, (as I mentioned in the previous review)


```
    if (is.logical(densContour)) {
        if (densContour == TRUE) {
            densContour <- dContours(xYData)
        }
    }
```

vs

```
 if (is.logical(densContour)) {
    if (densContour) {
       ...
    }
 }
 ```

This is because the "if" statement is entered only if the logical
value is TRUE. It will not enter the if statement otherwise. The idea
that you are checking logical values to be "equal" to TRUE is a wasted
operation since you are worried about efficieny in performance. You
are doing this in your codebase even now, please check all the places.

* I would like to see your benchmarking test for in dOptPenalty, where
  you test

```
param <- BiocParallel::SnowParam(workers = snowWorkers(type), type="SOCK")

register(param)

bplapply(list, your_function())
```

* You are right about `seq_along()` that was a typo on my end.

**Comment by jtheorell** [comment]
Dear @nturaga, 
Thank you again for these questions, and sorry for my misunderstandings. Below are point-by-point replies to the remaining issues. A new version of the package will be submitted where the changes and further optimizations, following your suggestions from the last round, have been incorporated.

## Vignette
* vignette doesn't render BiocStyle CSS. Please make sure you are
using it the right way.
**This has hopefully been corrected now, following the [simpleSingleCell](https://bioconductor.org/packages/release/workflows/html/simpleSingleCell.html) vignettes.**
* The vignette should use smaller datasets. It's ok to have plots in
the vignette, that is not a problem. Embed the graphs in your HTML
vignette. This is done by a lot of packages, and should not be an
issue. Do not use massive datasets, since it is software package,
your total package size should be less than 5MB.
**The dataset size has been made much smaller. In addition, the output from the visualization functions has been improved, making the output smaller and more succinct.**

## R
* You don't need to check if a logical value is "TRUE" in your "if"
statements, (as I mentioned in the previous review)
**I am sorry about this misunderstanding on my side. Of course all the "TRUE" values are unnecessary and have been removed in the current version.**

* I would like to see your benchmarking test for in dOptPenalty, where
you test
**For now, I only implemented this for dColorPlot, and the difference is striking even for a normal run with a small dataset, where parallelization would not be used in the default setting. And strangely, this follows when the dataset size is increased, so it is not just a matter of starting the workers more slowly. To make the comparison more fair, I have limited the number of used cores to 6 for the non-bpLapply version, as it would otherwise be 7.**

```
data(testData)
data(testDataSNE)

before <- Sys.time()
dColorPlot(colorData = testData, xYData = testDataSNE$Y, multiCore=TRUE, 
           nCores=6)
after <- Sys.time()-before
after

#Time difference of 7.048381 secs

before <- Sys.time()
dColorPlotBP(colorData = testData, xYData = testDataSNE$Y, multiCore=TRUE)
after <- Sys.time()-before
after

#Time difference of 12.5436 secs

#Now, the dataset size is increased 10-fold. 
testData10X <- do.call("rbind", replicate(10, testData, simplify = FALSE))

before <- Sys.time()
dColorPlot(colorData = testData10X, xYData = testDataSNE$Y, multiCore=TRUE, 
           nCores=6)
after <- Sys.time()-before
after

#Time difference of 20.08805 secs

before <- Sys.time()
dColorPlotBP(colorData = testData10X, xYData = testDataSNE$Y, multiCore=TRUE)
after <- Sys.time()-before
after

#Time difference of 28.96708 secs
```
**So I am still not convinced why it is better to use bpLapply.**

**Comment by nturaga** [comment]
It's ok that you use the SNOW package directly in this case. I will accept the package, but i'm still not sure why it would be any different from BiocParallel, as it wraps SNOW in a straightforward manner. 

Best,

Nitesh

**Comment by jtheorell** [comment]
Thank you very much! I will try to check for reasons for that difference in future updates. 
Best regards
Jakob

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Theorell.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DepecheR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DepecheR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
